Universal Software Radio Peripheral: duc_control Class Reference
duc_control Class Reference
Public Member Functions
duc_control (usrp_standard_tx *u, int chan)
bool is_tx ()
bool set_dxc_freq (double dxc_freq)
double dxc_freq ()
Constructor & Destructor Documentation
duc_control::duc_control (usrp_standard_tx * u, int chan) inline
Member Function Documentation
double duc_control::dxc_freq () inline virtual
Implements dxc_control.
References usrp_tune_result::baseband_freq, freq_result_t::baseband_freq, usrp_standard_common::calc_dxc_freq(), usrp_tune_result::dxc_freq, dxc_control::dxc_freq(), usrp_tune_result::inverted, dxc_control::is_tx(), freq_result_t::ok, usrp_tune_result::residual_freq, dxc_control::set_dxc_freq(), and usrp_standard_tx::tx_freq().
bool duc_control::is_tx () inline virtual
Implements dxc_control.
bool duc_control::set_dxc_freq (double dxc_freq) inline virtual
Implements dxc_control.
References usrp_standard_tx::set_tx_freq().
The documentation for this class was generated from the following file:
usrp_standard.cc