Universal Software Radio Peripheral: db_basic_tx Class Reference
db_basic_tx Class Reference
#include <db_basic.h>
Public Member Functions
db_basic_tx (usrp_basic_sptr usrp, int which)
~db_basic_tx ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
double freq_min ()
double freq_max ()
struct freq_result_t set_freq (double target_freq)
bool set_gain (float gain)
bool is_quadrature ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Additional Inherited Members
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
virtual int _refclk_divisor ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_basic_tx::db_basic_tx (usrp_basic_sptr usrp, int which)
References gain_max(), gain_min(), and set_gain().
db_basic_tx::~db_basic_tx ()
Member Function Documentation
double db_basic_tx::freq_max () virtual
Implements db_base.
Reimplemented in db_lf_tx.
double db_basic_tx::freq_min () virtual
Implements db_base.
Reimplemented in db_lf_tx.
float db_basic_tx::gain_db_per_step () virtual
Implements db_base.
References usrp_basic::pga_db_per_step(), and db_base::usrp().
float db_basic_tx::gain_max () virtual
Implements db_base.
References usrp_basic::pga_max(), and db_base::usrp().
Referenced by db_basic_tx().
float db_basic_tx::gain_min () virtual
Implements db_base.
References usrp_basic::pga_min(), and db_base::usrp().
Referenced by db_basic_tx().
bool db_basic_tx::is_quadrature () virtual
Implements db_base.
struct freq_result_t db_basic_tx::set_freq (double target_freq) virtual
Implements db_base.
References freq_result_t::baseband_freq, and freq_result_t::ok.
bool db_basic_tx::set_gain (float gain) virtual
Implements db_base.
References db_base::d_which, freq_result_t::ok, usrp_basic::set_pga(), and db_base::usrp().
Referenced by db_basic_tx().
The documentation for this class was generated from the following files:
db_basic.h
db_basic.cc