Universal Software Radio Peripheral: db_tv_rx Class Reference
db_tv_rx Class Reference
#include <db_tv_rx.h>
Public Member Functions
db_tv_rx (usrp_basic_sptr usrp, int which, double first_IF, double second_IF)
~db_tv_rx ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
double freq_min ()
double freq_max ()
struct freq_result_t set_freq (double target_freq)
bool set_gain (float gain)
bool is_quadrature ()
bool spectrum_inverted ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool i_and_q_swapped ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Additional Inherited Members
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
virtual int _refclk_divisor ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_tv_rx::db_tv_rx (usrp_basic_sptr usrp, int which, double first_IF, double second_IF)
References db_base::bypass_adc_buffers(), gain_max(), gain_min(), and set_gain().
db_tv_rx::~db_tv_rx ()
References db_base::d_which, usrp_basic::set_pga(), db_base::usrp(), and usrp_basic::write_aux_dac().
Member Function Documentation
double db_tv_rx::freq_max () virtual
Implements db_base.
Referenced by set_freq().
double db_tv_rx::freq_min () virtual
Implements db_base.
Referenced by set_freq().
float db_tv_rx::gain_db_per_step () virtual
Implements db_base.
float db_tv_rx::gain_max () virtual
Implements db_base.
Referenced by db_tv_rx().
float db_tv_rx::gain_min () virtual
Implements db_base.
Referenced by db_tv_rx().
bool db_tv_rx::is_quadrature () virtual
Implements db_base.
struct freq_result_t db_tv_rx::set_freq (double target_freq) virtual
Implements db_base.
References control_byte_1(), control_byte_2(), freq_max(), freq_min(), int_seq_to_str(), db_base::usrp(), and usrp_basic::write_i2c().
bool db_tv_rx::set_gain (float gain) virtual
Implements db_base.
Referenced by db_tv_rx().
bool db_tv_rx::spectrum_inverted () virtual
Reimplemented from db_base.
The documentation for this class was generated from the following files:
db_tv_rx.h
db_tv_rx.cc