Universal Software Radio Peripheral: usrp_standard_rx Class Reference
usrp_standard_rx Class Reference
The C++ interface the receive side of the USRPThis is the recommended interface to USRP receive functionality for applications that use the USRP but not GNU Radio.
#include <usrp_standard.h>
Public Types
enum { FPGA_MODE_NORMAL = 0x00, FPGA_MODE_LOOPBACK = 0x01, FPGA_MODE_COUNTING = 0x02, FPGA_MODE_COUNTING_32BIT = 0x04 }
Public Member Functions
~usrp_standard_rx ()
bool set_decim_rate (unsigned int rate)
Set decimator rate. rate MUST BE EVEN and in [8, 256].
bool set_nchannels (int nchannels)
Set number of active channels. nchannels must be 1, 2 or 4.
bool set_mux (int mux)
Set input mux configuration.
int determine_rx_mux_value (const usrp_subdev_spec &ss)
int determine_rx_mux_value (const usrp_subdev_spec &ss_a, const usrp_subdev_spec &ss_b)
bool set_rx_freq (int channel, double freq)
set the frequency of the digital down converter.
bool set_fpga_mode (int mode)
set fpga mode
bool set_ddc_phase (int channel, int phase)
Set the digital down converter phase register.
bool set_format (unsigned int format)
Specify Rx data format.
bool tune (int chan, db_base_sptr db, double target_freq, usrp_tune_result *result)
High-level "tune" method. Works for the single channel case.
unsigned int decim_rate () const
double rx_freq (int channel) const
int nchannels () const
int mux () const
unsigned int format () const
bool start ()
bool stop ()
Public Member Functions inherited from usrp_basic_rx
~usrp_basic_rx ()
bool set_fpga_rx_sample_rate_divisor (unsigned int div)
tell the fpga the rate rx samples are coming from the A/D's
int read (void *buf, int len, bool *overrun)
read data from the D/A's via the FPGA. len must be a multiple of 512 bytes.
virtual long converter_rate () const
sampling rate of A/D converter
long adc_rate () const
int daughterboard_id (int which_side) const
Return daughterboard ID for given side [0,1].
bool set_pga (int which_amp, double gain_in_db)
Set Programmable Gain Amplifier (PGA)
double pga (int which_amp) const
Return programmable gain amplifier gain setting in dB.
double pga_min () const
Return minimum legal PGA gain in dB.
double pga_max () const
Return maximum legal PGA gain in dB.
double pga_db_per_step () const
Return hardware step size of PGA (linear in dB).
bool _write_oe (int which_side, int value, int mask)
Write direction register (output enables) for pins that go to daughterboard.
bool write_io (int which_side, int value, int mask)
Write daughterboard i/o pin value.
bool read_io (int which_side, int *value)
Read daughterboard i/o pin value.
int read_io (int which_side)
Read daughterboard i/o pin value.
bool write_refclk (int which_side, int value)
Write daughterboard refclk config register.
bool write_atr_mask (int which_side, int value)
bool write_atr_txval (int which_side, int value)
bool write_atr_rxval (int which_side, int value)
bool write_aux_dac (int which_side, int which_dac, int value)
Write auxiliary digital to analog converter.
bool read_aux_adc (int which_side, int which_adc, int *value)
Read auxiliary analog to digital converter.
int read_aux_adc (int which_side, int which_adc)
Read auxiliary analog to digital converter.
int block_size () const
returns current fusb block size
bool start ()
bool stop ()
Public Member Functions inherited from usrp_basic
virtual ~usrp_basic ()
std::vector< std::vector< db_base_sptr > > db () const
std::vector< db_base_sptr > db (int which_side)
bool is_valid (const usrp_subdev_spec &ss)
is the subdev_spec valid?
db_base_sptr selected_subdev (const usrp_subdev_spec &ss)
given a subdev_spec, return the corresponding daughterboard object.
long fpga_master_clock_freq () const
return frequency of master oscillator on USRP
void set_fpga_master_clock_freq (long master_clock)
int usb_data_rate () const
void set_verbose (bool on)
bool write_eeprom (int i2c_addr, int eeprom_offset, const std::string buf)
Write EEPROM on motherboard or any daughterboard.
std::string read_eeprom (int i2c_addr, int eeprom_offset, int len)
Read EEPROM on motherboard or any daughterboard.
bool write_i2c (int i2c_addr, const std::string buf)
Write to I2C peripheral.
std::string read_i2c (int i2c_addr, int len)
Read from I2C peripheral.
bool set_adc_offset (int which_adc, int offset)
Set ADC offset correction.
bool set_dac_offset (int which_dac, int offset, int offset_pin)
Set DAC offset correction.
bool set_adc_buffer_bypass (int which_adc, bool bypass)
Control ADC input buffer.
bool set_dc_offset_cl_enable (int bits, int mask)
Enable/disable automatic DC offset removal control loop in FPGA.
std::string serial_number ()
return the usrp's serial number.
bool write_atr_tx_delay (int value)
Clock ticks to delay rising of T/R signal.
bool write_atr_rx_delay (int value)
Clock ticks to delay falling edge of T/R signal.
bool common_set_pga (txrx_t txrx, int which_amp, double gain_in_db)
Set Programmable Gain Amplifier(PGA)
double common_pga (txrx_t txrx, int which_amp) const
Return programmable gain amplifier gain setting in dB.
double common_pga_min (txrx_t txrx) const
Return minimum legal PGA gain in dB.
double common_pga_max (txrx_t txrx) const
Return maximum legal PGA gain in dB.
double common_pga_db_per_step (txrx_t txrx) const
Return hardware step size of PGA(linear in dB).
bool _common_write_oe (txrx_t txrx, int which_side, int value, int mask)
Write direction register(output enables) for pins that go to daughterboard.
bool common_write_io (txrx_t txrx, int which_side, int value, int mask)
Write daughterboard i/o pin value.
bool common_read_io (txrx_t txrx, int which_side, int *value)
Read daughterboard i/o pin value.
int common_read_io (txrx_t txrx, int which_side)
Read daughterboard i/o pin value.
bool common_write_refclk (txrx_t txrx, int which_side, int value)
Write daughterboard refclk config register.
bool common_write_atr_mask (txrx_t txrx, int which_side, int value)
Automatic Transmit/Receive switching.
bool common_write_atr_txval (txrx_t txrx, int which_side, int value)
bool common_write_atr_rxval (txrx_t txrx, int which_side, int value)
bool common_write_aux_dac (txrx_t txrx, int which_side, int which_dac, int value)
Write auxiliary digital to analog converter.
bool common_read_aux_adc (txrx_t txrx, int which_side, int which_adc, int *value)
Read auxiliary analog to digital converter.
int common_read_aux_adc (txrx_t txrx, int which_side, int which_adc)
Read auxiliary analog to digital converter.
bool _set_led (int which_led, bool on)
bool _write_fpga_reg (int regno, int value)
Write FPGA register.
bool _read_fpga_reg (int regno, int *value)
Read FPGA register.
int _read_fpga_reg (int regno)
Read FPGA register.
bool _write_fpga_reg_masked (int regno, int value, int mask)
Write FPGA register with mask.
bool _write_9862 (int which_codec, int regno, unsigned char value)
Write AD9862 register.
bool _read_9862 (int which_codec, int regno, unsigned char *value) const
Read AD9862 register.
int _read_9862 (int which_codec, int regno) const
Read AD9862 register.
bool _write_spi (int optional_header, int enables, int format, std::string buf)
Write data to SPI bus peripheral.
std::string _read_spi (int optional_header, int enables, int format, int len)
bool start ()
Start data transfers. Called in base class to derived class order.
bool stop ()
Stop data transfers. Called in base class to derived class order.
Public Member Functions inherited from usrp_standard_common
bool has_rx_halfband () const
does the FPGA implement the final Rx half-band filter? If it doesn't, the maximum decimation factor with proper gain is 1/2 of what it would otherwise be.
int nddcs () const
number of digital downconverters implemented in the FPGA This will be 0, 1, 2 or 4.
bool has_tx_halfband () const
does the FPGA implement the initial Tx half-band filter?
int nducs () const
number of digital upconverters implemented in the FPGA This will be 0, 1, or 2.
Static Public Member Functions
static usrp_standard_rx_sptr make (int which_board, unsigned int decim_rate, int nchan=1, int mux=-1, int mode=0, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
invokes constructor, returns shared_ptr or shared_ptr equivalent of 0 if trouble
static unsigned int make_format (int width=16, int shift=0, bool want_q=true, bool bypass_halfband=false)
static int format_width (unsigned int format)
static int format_shift (unsigned int format)
static bool format_want_q (unsigned int format)
static bool format_bypass_halfband (unsigned int format)
Static Public Member Functions inherited from usrp_basic_rx
static usrp_basic_rx * make (int which_board, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
invokes constructor, returns instance or 0 if trouble
Static Public Member Functions inherited from usrp_standard_common
static void calc_dxc_freq (double target_freq, double baseband_freq, double fs, double *dxc_freq, bool *inverted)
Calculate the frequency to use for setting the digital up or down converter.
Protected Member Functions
usrp_standard_rx (int which_board, unsigned int decim_rate, int nchan=1, int mux=-1, int mode=0, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
bool write_hw_mux_reg ()
Protected Member Functions inherited from usrp_basic_rx
usrp_basic_rx (int which_board, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
bool set_rx_enable (bool on)
bool rx_enable () const
bool disable_rx ()
void restore_rx (bool on)
void probe_rx_slots (bool verbose)
Protected Member Functions inherited from usrp_basic
void shutdown_daughterboards ()
void init_db (usrp_basic_sptr u)
usrp_basic (int which_board, libusb_device_handle *open_interface(libusb_device *dev), const std::string fpga_filename="", const std::string firmware_filename="")
void set_usb_data_rate (int usb_data_rate)
advise usrp_basic of usb data rate (bytes/sec)
bool _write_aux_dac (int slot, int which_dac, int value)
Write auxiliary digital to analog converter.
bool _read_aux_adc (int slot, int which_adc, int *value)
Read auxiliary analog to digital converter.
int _read_aux_adc (int slot, int which_adc)
Read auxiliary analog to digital converter.
Protected Member Functions inherited from usrp_standard_common
usrp_standard_common (usrp_basic *parent)
Additional Inherited Members
Static Public Attributes inherited from usrp_basic
static const int READ_FAILED = -99999
magic value used on alternate register read interfaces
Protected Attributes inherited from usrp_basic
libusb_device_handle * d_udh
struct libusb_context * d_ctx
int d_usb_data_rate
int d_bytes_per_poll
bool d_verbose
long d_fpga_master_clock_freq
unsigned int d_fpga_shadows [MAX_REGS]
int d_dbid [2]
std::vector< std::vector< db_base_sptr > > d_db
Static Protected Attributes inherited from usrp_basic
static const int MAX_REGS = 128
Detailed Description
The C++ interface the receive side of the USRP
This is the recommended interface to USRP receive functionality for applications that use the USRP but not GNU Radio.
Member Enumeration Documentation
anonymous enum
Enumerator
FPGA_MODE_NORMAL
FPGA_MODE_LOOPBACK
FPGA_MODE_COUNTING
FPGA_MODE_COUNTING_32BIT
Constructor & Destructor Documentation
usrp_standard_rx::usrp_standard_rx (int which_board, unsigned int decim_rate, int nchan = 1, int mux = -1, int mode = 0, int fusb_block_size = 0, int fusb_nblocks = 0, const std::string fpga_filename = "", const std::string firmware_filename = "") protected
References make_format(), set_ddc_phase(), set_decim_rate(), set_format(), set_fpga_mode(), set_mux(), set_nchannels(), and set_rx_freq().
Referenced by make().
usrp_standard_rx::~usrp_standard_rx ()
Member Function Documentation
unsigned int usrp_standard_rx::decim_rate () const
int usrp_standard_rx::determine_rx_mux_value (const usrp_subdev_spec & ss)
Determine the appropriate Rx mux value as a function of the subdevice choosen and the characteristics of the respective daughterboard.
References usrp_basic::db(), usrp_basic::is_valid(), usrp_subdev_spec::side, and usrp_subdev_spec::subdev.
Referenced by determine_rx_mux_value().
int usrp_standard_rx::determine_rx_mux_value (const usrp_subdev_spec & ss_a, const usrp_subdev_spec & ss_b)
References usrp_basic::db(), determine_rx_mux_value(), usrp_subdev_spec::side, and usrp_subdev_spec::subdev.
unsigned int usrp_standard_rx::format () const
References usrp_basic::d_fpga_shadows.
Referenced by make_format(), and set_ddc_phase().
bool usrp_standard_rx::format_bypass_halfband (unsigned int format) static
int usrp_standard_rx::format_shift (unsigned int format) static
bool usrp_standard_rx::format_want_q (unsigned int format) static
Referenced by set_ddc_phase().
int usrp_standard_rx::format_width (unsigned int format) static
Referenced by set_ddc_phase().
usrp_standard_rx_sptr usrp_standard_rx::make (int which_board, unsigned int decim_rate, int nchan = 1, int mux = -1, int mode = 0, int fusb_block_size = 0, int fusb_nblocks = 0, const std::string fpga_filename = "", const std::string firmware_filename = "") static
invokes constructor, returns shared_ptr or shared_ptr equivalent of 0 if trouble
Parameters
which_board Which USRP board on usb (not particularly useful; use 0)
decim_rate decimation factor
nchan number of channels
mux Rx mux setting,
See also
set_mux
Parameters
mode mode
fusb_block_size fast usb xfer block size. Must be a multiple of 512. Use zero for a reasonable default.
fusb_nblocks number of fast usb URBs to allocate. Use zero for a reasonable default.
fpga_filename Name of rbf file to load
firmware_filename Name of ihx file to load
References usrp_standard_rx().
Referenced by main().
unsigned int usrp_standard_rx::make_format (int width = 16, int shift = 0, bool want_q = true, bool bypass_halfband = false) static
References format().
Referenced by main(), and usrp_standard_rx().
int usrp_standard_rx::mux () const
Referenced by set_mux(), and tune().
int usrp_standard_rx::nchannels () const
Referenced by set_decim_rate().
double usrp_standard_rx::rx_freq (int channel) const
Referenced by ddc_control::dxc_freq().
bool usrp_standard_rx::set_ddc_phase (int channel, int phase)
Set the digital down converter phase register.
Parameters
channel which ddc channel [0, 3]
phase 32-bit integer phase value.
References usrp_basic::_write_fpga_reg(), format(), format_want_q(), and format_width().
Referenced by usrp_standard_rx().
bool usrp_standard_rx::set_decim_rate (unsigned int rate)
Set decimator rate. rate MUST BE EVEN and in [8, 256].
The final complex sample rate across the USB is adc_freq () / decim_rate () * nchannels ()
References usrp_basic::_write_fpga_reg(), usrp_basic_rx::adc_rate(), usrp_basic_rx::disable_rx(), usrp_standard_common::has_rx_halfband(), nchannels(), usrp_basic_rx::restore_rx(), and usrp_basic::set_usb_data_rate().
Referenced by usrp_standard_rx().
bool usrp_standard_rx::set_format (unsigned int format)
Specify Rx data format.
Parameters
format format specifier
Rx data format control register
3                   2                   1
1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 +--------------------------------------—+-+-+------—+----—+ | Reserved (Must be zero) |B|Q| WIDTH | SHIFT | +--------------------------------------—+-+-+------—+----—+
SHIFT specifies arithmetic right shift [0, 15] WIDTH specifies bit-width of I & Q samples across the USB [1, 16] (not all valid) Q if set deliver both I & Q, else just I B if set bypass half-band filter.
Right now the acceptable values are:
B Q WIDTH SHIFT 0 1 16 0 0 1 8 8
More valid combos to come.
Default value is 0x00000300 16-bits, 0 shift, deliver both I & Q.
References usrp_basic::_write_fpga_reg().
Referenced by usrp_standard_rx().
bool usrp_standard_rx::set_fpga_mode (int mode)
set fpga mode
References usrp_basic::_write_fpga_reg().
Referenced by usrp_standard_rx().
bool usrp_standard_rx::set_mux (int mux)
Set input mux configuration.
This determines which ADC (or constant zero) is connected to each DDC input. There are 4 DDCs. Each has two inputs.
Mux value:
   3                   2                   1
 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
+----—+----—+----—+----—+----—+----—+----—+----—+
|   Q3  |   I3  |   Q2  |   I2  |   Q1  |   I1  |   Q0  |   I0  |
+----—+----—+----—+----—+----—+----—+----—+----—+
Each 4-bit I field is either 0,1,2,3
Each 4-bit Q field is either 0,1,2,3 or 0xf (input is const zero)
All Q's must be 0xf or none of them may be 0xf
References mux(), and write_hw_mux_reg().
Referenced by usrp_standard_rx().
bool usrp_standard_rx::set_nchannels (int nchannels)
Set number of active channels. nchannels must be 1, 2 or 4.
The final complex sample rate across the USB is adc_freq () / decim_rate () * nchannels ()
References usrp_standard_common::nddcs(), and write_hw_mux_reg().
Referenced by usrp_standard_rx().
bool usrp_standard_rx::set_rx_freq (int channel, double freq)
set the frequency of the digital down converter.
channel must be in the range [0,3]. freq is the center frequency in Hz. freq may be either negative or postive. The frequency specified is quantized. Use rx_freq to retrieve the actual value used.
References usrp_basic::_write_fpga_reg(), usrp_basic_rx::adc_rate(), and usrp_basic::d_verbose.
Referenced by ddc_control::set_dxc_freq(), and usrp_standard_rx().
bool usrp_standard_rx::start ()
References usrp_basic_rx::start().
bool usrp_standard_rx::stop ()
References usrp_basic_rx::stop().
bool usrp_standard_rx::tune (int chan, db_base_sptr db, double target_freq, usrp_tune_result * result)
High-level "tune" method. Works for the single channel case.
This method adjusts both the daughterboard LO and the DDC so that target_freq ends up at DC in the complex baseband samples.
Parameters
chan which DDC channel we're controlling (almost always 0).
db the daughterboard we're controlling.
target_freq the RF frequency we want at DC in the complex baseband.
[out] result details how the hardware was configured.
Returns
true iff everything was successful.
References usrp_basic_rx::converter_rate(), mux(), REG_TX_DIGITAL, REG_TX_IF, TX_DIGITAL_2_DATA_PATHS, TX_DIGITAL_INTERPOLATE_4X, TX_IF_2S_COMP, TX_IF_I_FIRST, TX_IF_INTERLEAVED, and TX_IF_USE_CLKOUT1.
bool usrp_standard_rx::write_hw_mux_reg () protected
References usrp_basic::_write_fpga_reg(), usrp_basic_rx::disable_rx(), and usrp_basic_rx::restore_rx().
Referenced by set_mux(), and set_nchannels().
The documentation for this class was generated from the following files:
usrp_standard.h
usrp_standard.cc