Universal Software Radio Peripheral: circular_linked_list< T > Class Template Reference
circular_linked_list< T > Class Template Reference
#include <circular_linked_list.h>
Public Member Functions
circular_linked_list (size_t n_nodes)
~circular_linked_list ()
s_node_ptr find_next_available_node ()
void make_node_available (s_node_ptr l_node)
__INLINE__ void iterate_start ()
s_node_ptr iterate_next ()
__INLINE__ T object ()
__INLINE__ void object (T l_object)
__INLINE__ size_t num_nodes ()
__INLINE__ size_t num_used ()
__INLINE__ void num_used (size_t l_n_used)
__INLINE__ size_t num_available ()
__INLINE__ void num_used_inc (void)
__INLINE__ void num_used_dec (void)
__INLINE__ bool in_use ()
Constructor & Destructor Documentation
template<class T> circular_linked_list< T >::circular_linked_list (size_t n_nodes) inline
template<class T> circular_linked_list< T >::~circular_linked_list () inline
Member Function Documentation
template<class T> s_node_ptr circular_linked_list< T >::find_next_available_node () inline
Referenced by fusb_ephandle_darwin::write().
template<class T> __INLINE__ bool circular_linked_list< T >::in_use () inline
Referenced by fusb_ephandle_darwin::wait_for_completion().
template<class T> s_node_ptr circular_linked_list< T >::iterate_next () inline
Referenced by fusb_ephandle_darwin::start(), and fusb_ephandle_darwin::~fusb_ephandle_darwin().
template<class T> __INLINE__ void circular_linked_list< T >::iterate_start () inline
Referenced by fusb_ephandle_darwin::start(), and fusb_ephandle_darwin::~fusb_ephandle_darwin().
template<class T> void circular_linked_list< T >::make_node_available (s_node_ptr l_node) inline
Referenced by fusb_ephandle_darwin::write().
template<class T> __INLINE__ size_t circular_linked_list< T >::num_available () inline
template<class T> __INLINE__ size_t circular_linked_list< T >::num_nodes () inline
template<class T> __INLINE__ size_t circular_linked_list< T >::num_used () inline
Referenced by fusb_ephandle_darwin::start().
template<class T> __INLINE__ void circular_linked_list< T >::num_used (size_t l_n_used) inline
template<class T> __INLINE__ void circular_linked_list< T >::num_used_dec (void) inline
template<class T> __INLINE__ void circular_linked_list< T >::num_used_inc (void) inline
template<class T> __INLINE__ T circular_linked_list< T >::object () inline
template<class T> __INLINE__ void circular_linked_list< T >::object (T l_object) inline
The documentation for this class was generated from the following file:
circular_linked_list.h