Universal Software Radio Peripheral: db_base Class Reference
db_base Class Reference abstract
Abstract base class for all USRP daughterboards.
#include <db_base.h>
Public Member Functions
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual float gain_min ()=0
virtual float gain_max ()=0
virtual float gain_db_per_step ()=0
virtual double freq_min ()=0
virtual double freq_max ()=0
virtual struct freq_result_t set_freq (double target_freq)=0
virtual bool set_gain (float gain)=0
virtual bool is_quadrature ()=0
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Protected Member Functions
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
virtual int _refclk_divisor ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Friends
class usrp_basic
Detailed Description
Abstract base class for all USRP daughterboards.
Constructor & Destructor Documentation
db_base::db_base (boost::shared_ptr< usrp_basic > usrp, int which)
db_base::~db_base () virtual
References shutdown().
Member Function Documentation
void db_base::_enable_refclk (bool enable) protected
References _refclk_divisor(), usrp_basic::_write_oe(), CLOCK_OUT, d_which, usrp(), and usrp_basic::write_refclk().
Referenced by db_dbs_rx::db_dbs_rx(), db_flexrf_1200_rx_mimo_a::db_flexrf_1200_rx_mimo_a(), db_flexrf_1200_tx_mimo_a::db_flexrf_1200_tx_mimo_a(), db_flexrf_1800_rx_mimo_a::db_flexrf_1800_rx_mimo_a(), db_flexrf_1800_tx_mimo_a::db_flexrf_1800_tx_mimo_a(), db_flexrf_2400_rx_mimo_a::db_flexrf_2400_rx_mimo_a(), db_flexrf_2400_tx_mimo_a::db_flexrf_2400_tx_mimo_a(), db_flexrf_400_rx_mimo_a::db_flexrf_400_rx_mimo_a(), db_flexrf_400_tx_mimo_a::db_flexrf_400_tx_mimo_a(), db_flexrf_900_rx_mimo_a::db_flexrf_900_rx_mimo_a(), db_flexrf_900_tx_mimo_a::db_flexrf_900_tx_mimo_a(), db_tv_rx_mimo::db_tv_rx_mimo(), flexrf_base::flexrf_base(), db_wbxng_tx::shutdown(), db_dbs_rx::shutdown(), flexrf_base_tx::shutdown(), db_wbxng_rx::shutdown(), flexrf_base_rx::shutdown(), and wbxng_base::wbxng_base().
int db_base::_refclk_divisor () protected virtual
Reimplemented in db_flexrf_400_rx_mimo_b, db_flexrf_400_tx_mimo_b, db_flexrf_400_rx_mimo_a, db_flexrf_400_tx_mimo_a, db_flexrf_900_rx_mimo_b, db_flexrf_900_tx_mimo_b, db_flexrf_900_rx_mimo_a, db_flexrf_900_tx_mimo_a, db_flexrf_1200_rx_mimo_b, db_flexrf_1200_tx_mimo_b, db_flexrf_1200_rx_mimo_a, db_flexrf_1200_tx_mimo_a, db_flexrf_1800_rx_mimo_b, db_flexrf_1800_tx_mimo_b, db_flexrf_1800_rx_mimo_a, db_flexrf_1800_tx_mimo_a, flexrf_base, db_flexrf_2400_rx_mimo_b, wbxng_base, db_flexrf_2400_tx_mimo_b, db_flexrf_2400_rx_mimo_a, db_tv_rx_mimo, and db_flexrf_2400_tx_mimo_a.
Referenced by _enable_refclk(), and _refclk_freq().
double db_base::_refclk_freq () protected virtual
References _refclk_divisor(), usrp_basic::fpga_master_clock_freq(), and usrp().
Referenced by db_flexrf_2200_tx::_compute_regs(), db_flexrf_2200_rx::_compute_regs(), db_flexrf_2400_tx::_compute_regs(), db_flexrf_2400_rx::_compute_regs(), db_flexrf_1200_tx::_compute_regs(), db_flexrf_1200_rx::_compute_regs(), db_flexrf_1800_tx::_compute_regs(), db_flexrf_1800_rx::_compute_regs(), db_flexrf_900_tx::_compute_regs(), db_flexrf_900_rx::_compute_regs(), db_flexrf_400_tx::_compute_regs(), db_flexrf_400_rx::_compute_regs(), db_dbs_rx::set_bw(), wbxng_base::set_freq(), and db_dbs_rx::set_freq().
bool db_base::bypass_adc_buffers (bool bypass)
References d_which, usrp_basic::set_adc_buffer_bypass(), and usrp().
Referenced by db_basic_rx::db_basic_rx(), db_bitshark_rx::db_bitshark_rx(), db_dbs_rx::db_dbs_rx(), db_dtt754::db_dtt754(), db_dtt768::db_dtt768(), db_tv_rx::db_tv_rx(), db_wbxng_rx::db_wbxng_rx(), and flexrf_base_rx::flexrf_base_rx().
int db_base::dbid ()
References d_which, usrp_basic::daughterboard_id(), and usrp().
Referenced by name().
virtual double db_base::freq_max () pure virtual
Implemented in db_lf_tx, db_lf_rx, db_dbs_rx, db_basic_rx, db_tv_rx, db_xcvr2450_base, db_bitshark_rx, flexrf_base, db_basic_tx, db_dtt754, db_dtt768, and wbxng_base.
virtual double db_base::freq_min () pure virtual
Implemented in db_lf_tx, db_lf_rx, db_dbs_rx, db_basic_rx, db_tv_rx, db_xcvr2450_base, db_bitshark_rx, flexrf_base, db_basic_tx, db_dtt754, db_dtt768, and wbxng_base.
virtual float db_base::gain_db_per_step () pure virtual
Implemented in db_flexrf_400_rx, db_flexrf_900_rx, db_flexrf_1800_rx, db_flexrf_1200_rx, db_flexrf_2400_rx, db_flexrf_2200_rx, db_wbxng_rx, flexrf_base_tx, db_xcvr2450_rx, db_dbs_rx, db_wbxng_tx, db_xcvr2450_tx, db_basic_rx, db_tv_rx, db_bitshark_rx, db_basic_tx, db_dtt754, and db_dtt768.
virtual float db_base::gain_max () pure virtual
Implemented in db_flexrf_400_rx, db_flexrf_900_rx, db_flexrf_1800_rx, db_flexrf_1200_rx, db_flexrf_2400_rx, db_flexrf_2200_rx, db_wbxng_rx, flexrf_base_tx, db_xcvr2450_rx, db_dbs_rx, db_wbxng_tx, db_xcvr2450_tx, db_basic_rx, db_tv_rx, db_bitshark_rx, db_basic_tx, db_dtt754, and db_dtt768.
Referenced by flexrf_base_rx::set_gain().
virtual float db_base::gain_min () pure virtual
Implemented in db_flexrf_400_rx, db_flexrf_900_rx, db_flexrf_1800_rx, db_flexrf_1200_rx, db_flexrf_2400_rx, db_flexrf_2200_rx, db_wbxng_rx, flexrf_base_tx, db_xcvr2450_rx, db_dbs_rx, db_wbxng_tx, db_xcvr2450_tx, db_basic_rx, db_tv_rx, db_bitshark_rx, db_basic_tx, db_dtt754, and db_dtt768.
Referenced by flexrf_base_rx::set_gain().
bool db_base::i_and_q_swapped () virtual
Reimplemented in db_flexrf_400_rx, db_flexrf_900_rx, db_flexrf_1800_rx, db_flexrf_1200_rx, db_flexrf_2400_rx, db_flexrf_2200_rx, db_wbxng_rx, db_xcvr2450_tx, and db_bitshark_rx.
virtual bool db_base::is_quadrature () pure virtual
Implemented in db_dbs_rx, db_basic_rx, db_bitshark_rx, db_tv_rx, db_xcvr2450_base, db_basic_tx, db_dtt754, db_dtt768, flexrf_base, and wbxng_base.
double db_base::lo_offset () inline
std::string db_base::name ()
References dbid(), and usrp_dbid_to_string().
Referenced by side_and_name().
bool db_base::select_rx_antenna (int which_antenna) virtual
Reimplemented in flexrf_base_rx, and db_wbxng_rx.
bool db_base::select_rx_antenna (const std::string & which_antenna) virtual
Reimplemented in flexrf_base_rx, and db_wbxng_rx.
bool db_base::set_atr_mask (int v)
References d_which, usrp(), and usrp_basic::write_atr_mask().
Referenced by db_wbxng_tx::set_auto_tr(), db_wbxng_rx::set_auto_tr(), flexrf_base_tx::set_auto_tr(), and flexrf_base_rx::set_auto_tr().
bool db_base::set_atr_rx_delay (int v)
References usrp(), and usrp_basic::write_atr_rx_delay().
bool db_base::set_atr_rxval (int v)
References d_which, usrp(), and usrp_basic::write_atr_rxval().
Referenced by db_wbxng_tx::set_auto_tr(), db_wbxng_rx::set_auto_tr(), flexrf_base_tx::set_auto_tr(), and flexrf_base_rx::set_auto_tr().
bool db_base::set_atr_tx_delay (int v)
References usrp(), and usrp_basic::write_atr_tx_delay().
bool db_base::set_atr_txval (int v)
References d_which, usrp(), and usrp_basic::write_atr_txval().
Referenced by db_wbxng_tx::set_auto_tr(), db_wbxng_rx::set_auto_tr(), flexrf_base_tx::set_auto_tr(), and flexrf_base_rx::set_auto_tr().
bool db_base::set_auto_tr (bool on) virtual
Reimplemented in flexrf_base_rx, flexrf_base_tx, db_wbxng_rx, and db_wbxng_tx.
Referenced by flexrf_base::flexrf_base(), and wbxng_base::wbxng_base().
bool db_base::set_bw (float bw) virtual
Reimplemented in db_dbs_rx, db_bitshark_rx, db_dtt754, and db_dtt768.
bool db_base::set_enable (bool on) virtual
Reimplemented in flexrf_base_tx, and db_wbxng_tx.
virtual struct freq_result_t db_base::set_freq (double target_freq) pure virtual
Implemented in db_dbs_rx, db_basic_rx, db_tv_rx, db_bitshark_rx, db_xcvr2450_base, db_basic_tx, db_dtt754, db_dtt768, flexrf_base, and wbxng_base.
virtual bool db_base::set_gain (float gain) pure virtual
Implemented in flexrf_base_rx, flexrf_base_tx, db_wbxng_rx, db_xcvr2450_rx, db_dbs_rx, db_wbxng_tx, db_xcvr2450_tx, db_basic_rx, db_tv_rx, db_bitshark_rx, db_basic_tx, db_dtt754, and db_dtt768.
bool db_base::set_lo_offset (double offset)
References d_lo_offset.
Referenced by db_xcvr2450_rx::db_xcvr2450_rx(), db_xcvr2450_tx::db_xcvr2450_tx(), flexrf_base_rx::flexrf_base_rx(), and flexrf_base_tx::flexrf_base_tx().
void db_base::shutdown () protected virtual
Called to shutdown daughterboard. Called from dtor and usrp_basic dtor.
N.B., any class that overrides shutdown MUST call shutdown in its destructor.
Reimplemented in flexrf_base_rx, db_wbxng_rx, db_xcvr2450_rx, flexrf_base_tx, db_dbs_rx, db_wbxng_tx, db_xcvr2450_tx, and db_bitshark_rx.
References d_is_shutdown.
Referenced by ~db_base().
std::string db_base::side_and_name ()
References d_which, and name().
Referenced by operator<<().
bool db_base::spectrum_inverted () virtual
Reimplemented in db_tv_rx, db_dtt754, and db_dtt768.
usrp_basic* db_base::usrp () inline protected
References dbid, and name.
Referenced by _enable_refclk(), wbxng_base::_get_locked(), flexrf_base::_lock_detect(), _refclk_freq(), db_wbxng_rx::_set_attn(), wbxng_base::_set_pga(), flexrf_base::_set_pga(), flexrf_base::_write_it(), wbxng_base::_write_spi(), bypass_adc_buffers(), db_bitshark_rx::db_bitshark_rx(), db_dbs_rx::db_dbs_rx(), db_wbxng_rx::db_wbxng_rx(), db_wbxng_tx::db_wbxng_tx(), dbid(), flexrf_base::flexrf_base(), flexrf_base_rx::flexrf_base_rx(), flexrf_base_tx::flexrf_base_tx(), db_basic_tx::gain_db_per_step(), db_basic_rx::gain_db_per_step(), db_basic_tx::gain_max(), db_basic_rx::gain_max(), flexrf_base_tx::gain_max(), db_wbxng_rx::gain_max(), db_flexrf_2200_rx::gain_max(), db_flexrf_2400_rx::gain_max(), db_flexrf_1200_rx::gain_max(), db_flexrf_1800_rx::gain_max(), db_flexrf_900_rx::gain_max(), db_flexrf_400_rx::gain_max(), db_basic_tx::gain_min(), db_basic_rx::gain_min(), flexrf_base_tx::gain_min(), db_wbxng_rx::gain_min(), db_flexrf_2200_rx::gain_min(), db_flexrf_2400_rx::gain_min(), db_flexrf_1200_rx::gain_min(), db_flexrf_1800_rx::gain_min(), db_flexrf_900_rx::gain_min(), db_flexrf_400_rx::gain_min(), db_wbxng_rx::select_rx_antenna(), flexrf_base_rx::select_rx_antenna(), set_atr_mask(), set_atr_rx_delay(), set_atr_rxval(), set_atr_tx_delay(), set_atr_txval(), db_dtt754::set_bw(), db_dtt768::set_bw(), db_bitshark_rx::set_bw(), db_dbs_rx::set_bw(), db_bitshark_rx::set_clock_scheme(), db_wbxng_tx::set_enable(), flexrf_base_tx::set_enable(), db_dtt754::set_freq(), db_dtt768::set_freq(), db_bitshark_rx::set_freq(), db_tv_rx::set_freq(), db_basic_tx::set_gain(), db_bitshark_rx::set_gain(), db_basic_rx::set_gain(), db_wbxng_tx::set_gain(), db_wbxng_rx::set_gain(), flexrf_base_tx::set_gain(), flexrf_base_rx::set_gain(), db_wbxng_tx::shutdown(), db_dbs_rx::shutdown(), flexrf_base_tx::shutdown(), db_wbxng_rx::shutdown(), flexrf_base_rx::shutdown(), db_xcvr2450_base::shutdown_common(), wbxng_base::wbxng_base(), db_bitshark_rx::~db_bitshark_rx(), and db_tv_rx::~db_tv_rx().
int db_base::which () inline
Friends And Related Function Documentation
friend class usrp_basic friend
Member Data Documentation
bool db_base::d_is_shutdown protected
Referenced by db_bitshark_rx::shutdown(), db_xcvr2450_tx::shutdown(), db_wbxng_tx::shutdown(), db_dbs_rx::shutdown(), flexrf_base_tx::shutdown(), db_xcvr2450_rx::shutdown(), db_wbxng_rx::shutdown(), shutdown(), and flexrf_base_rx::shutdown().
double db_base::d_lo_offset protected
Referenced by flexrf_base::set_freq(), db_xcvr2450_base::set_freq(), and set_lo_offset().
usrp_basic* db_base::d_raw_usrp protected
int db_base::d_which protected
Referenced by _enable_refclk(), wbxng_base::_get_locked(), flexrf_base::_lock_detect(), db_wbxng_rx::_set_attn(), wbxng_base::_set_pga(), flexrf_base::_set_pga(), bypass_adc_buffers(), db_bitshark_rx::db_bitshark_rx(), db_dbs_rx::db_dbs_rx(), db_dtt754::db_dtt754(), db_dtt768::db_dtt768(), db_wbxng_rx::db_wbxng_rx(), db_wbxng_tx::db_wbxng_tx(), dbid(), flexrf_base::flexrf_base(), flexrf_base_rx::flexrf_base_rx(), flexrf_base_tx::flexrf_base_tx(), db_wbxng_rx::select_rx_antenna(), flexrf_base_rx::select_rx_antenna(), set_atr_mask(), set_atr_rxval(), set_atr_txval(), db_dtt768::set_bw(), db_dtt754::set_bw(), db_dbs_rx::set_bw(), db_wbxng_tx::set_enable(), flexrf_base_tx::set_enable(), db_basic_tx::set_gain(), db_basic_rx::set_gain(), db_wbxng_tx::set_gain(), flexrf_base_rx::set_gain(), db_wbxng_tx::shutdown(), flexrf_base_tx::shutdown(), db_wbxng_rx::shutdown(), flexrf_base_rx::shutdown(), side_and_name(), wbxng_base::wbxng_base(), db_bitshark_rx::~db_bitshark_rx(), and db_tv_rx::~db_tv_rx().
The documentation for this class was generated from the following files:
db_base.h
db_base.cc