Universal Software Radio Peripheral: fusb_ephandle_linux Class Reference
fusb_ephandle_linux Class Reference
linux specific implementation of fusb_ephandle using usbdevice_fs
#include <fusb_linux.h>
Public Member Functions
fusb_ephandle_linux (fusb_devhandle_linux *dh, int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle_linux ()
virtual bool start ()
begin streaming i/o
virtual bool stop ()
stop streaming i/o
virtual int write (const void *buffer, int nbytes)
virtual int read (void *buffer, int nbytes)
virtual void wait_for_completion ()
void free_list_add (usbdevfs_urb *urb)
void completed_list_add (usbdevfs_urb *urb)
usbdevfs_urb * free_list_get ()
usbdevfs_urb * completed_list_get ()
Public Member Functions inherited from fusb_ephandle
fusb_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle ()
int block_size ()
returns current block size.
Additional Inherited Members
Protected Attributes inherited from fusb_ephandle
int d_endpoint
bool d_input_p
int d_block_size
int d_nblocks
bool d_started
Detailed Description
linux specific implementation of fusb_ephandle using usbdevice_fs
Constructor & Destructor Documentation
fusb_ephandle_linux::fusb_ephandle_linux (fusb_devhandle_linux * dh, int endpoint, bool input_p, int block_size = 0, int nblocks = 0)
References fusb_ephandle::d_block_size, fusb_ephandle::d_endpoint, fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, and MINIMIZE_TX_BUFFERING.
fusb_ephandle_linux::~fusb_ephandle_linux () virtual
References completed_list_get(), free_list_get(), and stop().
Member Function Documentation
void fusb_ephandle_linux::completed_list_add (usbdevfs_urb * urb)
Referenced by fusb_devhandle_linux::_reap().
usbdevfs_urb * fusb_ephandle_linux::completed_list_get ()
References fusb_devhandle_linux::_submit_urb(), and free_list_add().
Referenced by read(), stop(), write(), and ~fusb_ephandle_linux().
void fusb_ephandle_linux::free_list_add (usbdevfs_urb * urb)
Referenced by completed_list_get(), read(), stop(), and write().
usbdevfs_urb * fusb_ephandle_linux::free_list_get ()
Referenced by start(), write(), and ~fusb_ephandle_linux().
int fusb_ephandle_linux::read (void * buffer, int nbytes) virtual
Returns
number of bytes read or -1 if error. number of bytes read will be <= nbytes. Will block if no input available.
Implements fusb_ephandle.
References fusb_devhandle_linux::_reap(), completed_list_get(), fusb_ephandle::d_input_p, fusb_ephandle::d_started, and free_list_add().
bool fusb_ephandle_linux::start () virtual
begin streaming i/o
Implements fusb_ephandle.
References fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, fusb_ephandle::d_started, and free_list_get().
bool fusb_ephandle_linux::stop () virtual
stop streaming i/o
Implements fusb_ephandle.
References fusb_devhandle_linux::_cancel_pending_rqsts(), fusb_devhandle_linux::_reap(), completed_list_get(), fusb_ephandle::d_nblocks, fusb_ephandle::d_started, and free_list_add().
Referenced by ~fusb_ephandle_linux().
void fusb_ephandle_linux::wait_for_completion () virtual
Implements fusb_ephandle.
References fusb_devhandle_linux::_wait_for_completion().
int fusb_ephandle_linux::write (const void * buffer, int nbytes) virtual
Returns
nbytes if write was successfully enqueued, else -1. Will block if no free buffers available.
Implements fusb_ephandle.
References fusb_devhandle_linux::_reap(), completed_list_get(), fusb_ephandle::d_input_p, fusb_ephandle::d_started, free_list_add(), and free_list_get().
The documentation for this class was generated from the following files:
fusb_linux.h
fusb_linux.cc