Universal Software Radio Peripheral: db_xcvr2450_base Class Reference
db_xcvr2450_base Class Reference
#include <db_xcvr2450.h>
Public Member Functions
db_xcvr2450_base (usrp_basic_sptr usrp, int which)
~db_xcvr2450_base ()
struct freq_result_t set_freq (double target_freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual float gain_min ()=0
virtual float gain_max ()=0
virtual float gain_db_per_step ()=0
virtual bool set_gain (float gain)=0
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Protected Member Functions
void shutdown_common ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
virtual int _refclk_divisor ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes
xcvr2450_sptr d_xcvr
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_xcvr2450_base::db_xcvr2450_base (usrp_basic_sptr usrp, int which)
References d_xcvr.
db_xcvr2450_base::~db_xcvr2450_base ()
Member Function Documentation
double db_xcvr2450_base::freq_max () virtual
Implements db_base.
double db_xcvr2450_base::freq_min () virtual
Implements db_base.
bool db_xcvr2450_base::is_quadrature () virtual
Implements db_base.
struct freq_result_t db_xcvr2450_base::set_freq (double target_freq) virtual
Implements db_base.
References db_base::d_lo_offset, and d_xcvr.
void db_xcvr2450_base::shutdown_common () protected
References d_xcvr, and db_base::usrp().
Referenced by db_xcvr2450_tx::shutdown(), and db_xcvr2450_rx::shutdown().
Member Data Documentation
xcvr2450_sptr db_xcvr2450_base::d_xcvr protected
Referenced by db_xcvr2450_base(), set_freq(), db_xcvr2450_tx::set_gain(), db_xcvr2450_rx::set_gain(), and shutdown_common().
The documentation for this class was generated from the following files:
db_xcvr2450.h
db_xcvr2450.cc