Universal Software Radio Peripheral: flexrf_base_tx Class Reference
flexrf_base_tx Class Reference
#include <db_flexrf.h>
Public Member Functions
flexrf_base_tx (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base_tx ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
bool set_auto_tr (bool on)
bool set_enable (bool on)
bool set_gain (float gain)
Public Member Functions inherited from flexrf_base
flexrf_base (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base ()
struct freq_result_t set_freq (double freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Protected Member Functions
void shutdown ()
Protected Member Functions inherited from flexrf_base
void _write_all (int R, int control, int N)
void _write_control (int control)
void _write_R (int R)
void _write_N (int N)
void _write_it (int v)
bool _lock_detect ()
virtual bool _compute_regs (double freq, int &retR, int &retcontrol, int &retN, double &retfreq)
int _compute_control_reg ()
int _refclk_divisor ()
bool _set_pga (float pga_gain)
int power_on ()
int power_off ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
Additional Inherited Members
Protected Attributes inherited from flexrf_base
bool d_first
int d_spi_format
int d_spi_enable
int d_power_on
int d_PD
_AD4360_common * d_common
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
flexrf_base_tx::flexrf_base_tx (usrp_basic_sptr usrp, int which, int _power_on = 0)
References usrp_basic::_write_oe(), flexrf_base::d_spi_enable, db_base::d_which, ENABLE, gain_max(), gain_min(), flexrf_base::power_on(), POWER_UP, RX_TXN, set_gain(), db_base::set_lo_offset(), db_base::usrp(), and usrp_basic::write_io().
flexrf_base_tx::~flexrf_base_tx ()
References shutdown().
Member Function Documentation
float flexrf_base_tx::gain_db_per_step () virtual
Implements db_base.
float flexrf_base_tx::gain_max () virtual
Implements db_base.
References usrp_basic::pga_max(), and db_base::usrp().
Referenced by flexrf_base_tx().
float flexrf_base_tx::gain_min () virtual
Implements db_base.
References usrp_basic::pga_max(), and db_base::usrp().
Referenced by flexrf_base_tx().
bool flexrf_base_tx::set_auto_tr (bool on) virtual
Reimplemented from db_base.
References ENABLE, freq_result_t::ok, RX_TXN, db_base::set_atr_mask(), db_base::set_atr_rxval(), and db_base::set_atr_txval().
Referenced by shutdown().
bool flexrf_base_tx::set_enable (bool on) virtual
Reimplemented from db_base.
References db_base::d_which, ENABLE, RX_TXN, db_base::usrp(), and usrp_basic::write_io().
bool flexrf_base_tx::set_gain (float gain) virtual
Implements db_base.
References flexrf_base::_set_pga(), and db_base::usrp().
Referenced by flexrf_base_tx().
void flexrf_base_tx::shutdown () protected virtual
Called to shutdown daughterboard. Called from dtor and usrp_basic dtor.
N.B., any class that overrides shutdown MUST call shutdown in its destructor.
Reimplemented from db_base.
References flexrf_base::_compute_control_reg(), db_base::_enable_refclk(), flexrf_base::_write_control(), db_base::d_is_shutdown, flexrf_base::d_PD, db_base::d_which, ENABLE, flexrf_base::power_off(), POWER_UP, RX_TXN, set_auto_tr(), db_base::usrp(), and usrp_basic::write_io().
Referenced by ~flexrf_base_tx().
The documentation for this class was generated from the following files:
db_flexrf.h
db_flexrf.cc