Universal Software Radio Peripheral: s_node< T > Class Template Reference
s_node< T > Class Template Reference
#include <circular_linked_list.h>
Public Member Functions
s_node (T l_object, s_node_ptr l_prev=NULL, s_node_ptr l_next=NULL)
__INLINE__ s_node (s_node_ptr l_prev, s_node_ptr l_next=NULL)
__INLINE__ s_node ()
__INLINE__ ~s_node ()
void remove ()
void insert_before (s_node_ptr l_next)
void insert_after (s_node_ptr l_prev)
__INLINE__ T object ()
__INLINE__ void object (T l_object)
__INLINE__ bool available ()
__INLINE__ void set_available ()
__INLINE__ void set_available (bool l_avail)
__INLINE__ void set_not_available ()
__INLINE__ s_node_ptr next ()
__INLINE__ s_node_ptr prev ()
__INLINE__ s_both< T > * both ()
__INLINE__ void next (s_node_ptr l_next)
__INLINE__ void prev (s_node_ptr l_prev)
__INLINE__ void both (s_both< T > *l_both)
Constructor & Destructor Documentation
template<class T> s_node< T >::s_node (T l_object, s_node_ptr l_prev = NULL, s_node_ptr l_next = NULL) inline
template<class T> __INLINE__ s_node< T >::s_node (s_node_ptr l_prev, s_node_ptr l_next = NULL) inline
template<class T> __INLINE__ s_node< T >::s_node () inline
Referenced by s_node< s_buffer_ptr >::s_node().
template<class T> __INLINE__ s_node< T >::~s_node () inline
Member Function Documentation
template<class T> __INLINE__ bool s_node< T >::available () inline
template<class T> __INLINE__ s_both<T>* s_node< T >::both () inline
Referenced by fusb_ephandle_darwin::fusb_ephandle_darwin(), fusb_ephandle_darwin::start(), fusb_ephandle_darwin::write(), and fusb_ephandle_darwin::~fusb_ephandle_darwin().
template<class T> __INLINE__ void s_node< T >::both (s_both< T > * l_both) inline
template<class T> void s_node< T >::insert_after (s_node_ptr l_prev) inline
template<class T> void s_node< T >::insert_before (s_node_ptr l_next) inline
Referenced by circular_linked_list< s_buffer_ptr >::find_next_available_node(), and circular_linked_list< s_buffer_ptr >::make_node_available().
template<class T> __INLINE__ s_node_ptr s_node< T >::next () inline
Referenced by circular_linked_list< s_buffer_ptr >::circular_linked_list(), circular_linked_list< s_buffer_ptr >::find_next_available_node(), s_node< s_buffer_ptr >::insert_after(), s_node< s_buffer_ptr >::insert_before(), circular_linked_list< s_buffer_ptr >::iterate_next(), circular_linked_list< s_buffer_ptr >::make_node_available(), and s_node< s_buffer_ptr >::remove().
template<class T> __INLINE__ void s_node< T >::next (s_node_ptr l_next) inline
template<class T> __INLINE__ T s_node< T >::object () inline
Referenced by fusb_ephandle_darwin::fusb_ephandle_darwin(), fusb_ephandle_darwin::start(), fusb_ephandle_darwin::write(), and fusb_ephandle_darwin::~fusb_ephandle_darwin().
template<class T> __INLINE__ void s_node< T >::object (T l_object) inline
template<class T> __INLINE__ s_node_ptr s_node< T >::prev () inline
Referenced by circular_linked_list< s_buffer_ptr >::circular_linked_list(), s_node< s_buffer_ptr >::insert_after(), s_node< s_buffer_ptr >::insert_before(), and s_node< s_buffer_ptr >::remove().
template<class T> __INLINE__ void s_node< T >::prev (s_node_ptr l_prev) inline
template<class T> void s_node< T >::remove () inline
Referenced by circular_linked_list< s_buffer_ptr >::find_next_available_node(), and circular_linked_list< s_buffer_ptr >::make_node_available().
template<class T> __INLINE__ void s_node< T >::set_available () inline
Referenced by circular_linked_list< s_buffer_ptr >::circular_linked_list(), and fusb_ephandle_darwin::start().
template<class T> __INLINE__ void s_node< T >::set_available (bool l_avail) inline
template<class T> __INLINE__ void s_node< T >::set_not_available () inline
Referenced by circular_linked_list< s_buffer_ptr >::find_next_available_node().
The documentation for this class was generated from the following file:
circular_linked_list.h