Universal Software Radio Peripheral: usrp_signal Class Reference
usrp_signal Class Reference
Representation of signal.
#include <usrp_local_sighandler.h>
Public Member Functions
usrp_signal (int signum)
int signal () const
std::string name () const
Detailed Description
Representation of signal.
Constructor & Destructor Documentation
usrp_signal::usrp_signal (int signum) inline
Member Function Documentation
std::string usrp_signal::name () const
References SIGNAME.
Referenced by main(), and signal().
int usrp_signal::signal () const inline
References name().
The documentation for this class was generated from the following files:
usrp_local_sighandler.h
usrp_local_sighandler.cc