Universal Software Radio Peripheral: flexrf_base_rx Class Reference
flexrf_base_rx Class Reference
#include <db_flexrf.h>
Public Member Functions
flexrf_base_rx (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base_rx ()
bool set_auto_tr (bool on)
bool select_rx_antenna (int which_antenna)
bool select_rx_antenna (const std::string &which_antenna)
bool set_gain (float gain)
Public Member Functions inherited from flexrf_base
flexrf_base (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base ()
struct freq_result_t set_freq (double freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual float gain_min ()=0
virtual float gain_max ()=0
virtual float gain_db_per_step ()=0
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_bw (float bw)
Protected Member Functions
void shutdown ()
Protected Member Functions inherited from flexrf_base
void _write_all (int R, int control, int N)
void _write_control (int control)
void _write_R (int R)
void _write_N (int N)
void _write_it (int v)
bool _lock_detect ()
virtual bool _compute_regs (double freq, int &retR, int &retcontrol, int &retN, double &retfreq)
int _compute_control_reg ()
int _refclk_divisor ()
bool _set_pga (float pga_gain)
int power_on ()
int power_off ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
Additional Inherited Members
Protected Attributes inherited from flexrf_base
bool d_first
int d_spi_format
int d_spi_enable
int d_power_on
int d_PD
_AD4360_common * d_common
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
flexrf_base_rx::flexrf_base_rx (usrp_basic_sptr usrp, int which, int _power_on = 0)
References usrp_basic::_write_oe(), db_base::bypass_adc_buffers(), flexrf_base::d_spi_enable, db_base::d_which, ENABLE, flexrf_base::power_on(), POWER_UP, RX2_RX1N, select_rx_antenna(), db_base::set_lo_offset(), db_base::usrp(), and usrp_basic::write_io().
flexrf_base_rx::~flexrf_base_rx ()
References shutdown().
Member Function Documentation
bool flexrf_base_rx::select_rx_antenna (int which_antenna) virtual
Reimplemented from db_base.
References db_base::d_which, RX2_RX1N, db_base::usrp(), and usrp_basic::write_io().
Referenced by flexrf_base_rx().
bool flexrf_base_rx::select_rx_antenna (const std::string & which_antenna) virtual
Reimplemented from db_base.
References db_base::d_which, RX2_RX1N, db_base::usrp(), and usrp_basic::write_io().
bool flexrf_base_rx::set_auto_tr (bool on) virtual
Reimplemented from db_base.
References ENABLE, freq_result_t::ok, db_base::set_atr_mask(), db_base::set_atr_rxval(), and db_base::set_atr_txval().
Referenced by shutdown().
bool flexrf_base_rx::set_gain (float gain) virtual
Implements db_base.
References flexrf_base::_set_pga(), db_base::d_which, db_base::gain_max(), db_base::gain_min(), usrp_basic::pga_max(), and db_base::usrp().
Referenced by db_flexrf_1200_rx::db_flexrf_1200_rx(), db_flexrf_1800_rx::db_flexrf_1800_rx(), db_flexrf_2200_rx::db_flexrf_2200_rx(), db_flexrf_2400_rx::db_flexrf_2400_rx(), db_flexrf_400_rx::db_flexrf_400_rx(), and db_flexrf_900_rx::db_flexrf_900_rx().
void flexrf_base_rx::shutdown () protected virtual
Called to shutdown daughterboard. Called from dtor and usrp_basic dtor.
N.B., any class that overrides shutdown MUST call shutdown in its destructor.
Reimplemented from db_base.
References flexrf_base::_compute_control_reg(), db_base::_enable_refclk(), flexrf_base::_write_control(), C_RX, usrp_basic::common_write_io(), db_base::d_is_shutdown, flexrf_base::d_PD, db_base::d_which, ENABLE, flexrf_base::power_off(), POWER_UP, set_auto_tr(), and db_base::usrp().
Referenced by ~flexrf_base_rx().
The documentation for this class was generated from the following files:
db_flexrf.h
db_flexrf.cc