Universal Software Radio Peripheral: fusb_sysconfig Class Reference
fusb_sysconfig Class Reference
factory for creating concrete instances of the appropriate subtype.
#include <fusb.h>
Static Public Member Functions
static fusb_devhandle * make_devhandle (libusb_device_handle *udh, libusb_context *ctx=0)
returns fusb_devhandle or throws if trouble
static int max_block_size ()
Returns max block size in bytes (hard limit).
static int default_block_size ()
Returns default block size in bytes.
static int default_buffer_size ()
Returns the default buffer size in bytes.
Detailed Description
factory for creating concrete instances of the appropriate subtype.
Member Function Documentation
int fusb_sysconfig::default_block_size () static
Returns default block size in bytes.
References max_block_size().
Referenced by usrp_basic_rx::usrp_basic_rx().
int fusb_sysconfig::default_buffer_size () static
Returns the default buffer size in bytes.
fusb_devhandle * fusb_sysconfig::make_devhandle (libusb_device_handle * udh, libusb_context * ctx = 0) static
returns fusb_devhandle or throws if trouble
Referenced by usrp_basic_rx::usrp_basic_rx(), and usrp_basic_tx::usrp_basic_tx().
int fusb_sysconfig::max_block_size () static
Returns max block size in bytes (hard limit).
Referenced by default_block_size(), and fusb_ephandle_darwin::fusb_ephandle_darwin().
The documentation for this class was generated from the following files:
fusb.h
fusb_sysconfig_darwin.cc
fusb_sysconfig_generic.cc
fusb_sysconfig_libusb1.cc
fusb_sysconfig_linux.cc
fusb_sysconfig_ra_wb.cc
fusb_sysconfig_win32.cc