Universal Software Radio Peripheral: circular_buffer< T > Class Template Reference
circular_buffer< T > Class Template Reference
#include <circular_buffer.h>
Public Member Functions
circular_buffer (size_t bufLen_I, bool doWriteBlock=true, bool doFullRead=false)
~circular_buffer ()
size_t n_avail_write_items ()
size_t n_avail_read_items ()
size_t buffer_length_items ()
bool do_write_block ()
bool do_full_read ()
void reset ()
int enqueue (T *buf, size_t bufLen_I)
int dequeue (T *buf, size_t *bufLen_I)
void abort ()
Constructor & Destructor Documentation
template<class T> circular_buffer< T >::circular_buffer (size_t bufLen_I, bool doWriteBlock = true, bool doFullRead = false) inline
template<class T> circular_buffer< T >::~circular_buffer () inline
Member Function Documentation
template<class T> void circular_buffer< T >::abort () inline
Referenced by fusb_ephandle_darwin::stop().
template<class T> size_t circular_buffer< T >::buffer_length_items () inline
template<class T> int circular_buffer< T >::dequeue (T * buf, size_t * bufLen_I) inline
Referenced by fusb_ephandle_darwin::read().
template<class T> bool circular_buffer< T >::do_full_read () inline
template<class T> bool circular_buffer< T >::do_write_block () inline
template<class T> int circular_buffer< T >::enqueue (T * buf, size_t bufLen_I) inline
Referenced by fusb_ephandle_darwin::start().
template<class T> size_t circular_buffer< T >::n_avail_read_items () inline
template<class T> size_t circular_buffer< T >::n_avail_write_items () inline
template<class T> void circular_buffer< T >::reset () inline
Referenced by circular_buffer< char >::circular_buffer(), and fusb_ephandle_darwin::start().
The documentation for this class was generated from the following file:
circular_buffer.h