Universal Software Radio Peripheral: fusb_ephandle_win32 Class Reference
fusb_ephandle_win32 Class Reference
win32 implementation of fusb_ephandle using libusb-win32
#include <fusb_win32.h>
Public Member Functions
fusb_ephandle_win32 (fusb_devhandle_win32 *dh, int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle_win32 ()
virtual bool start ()
begin streaming i/o
virtual bool stop ()
stop streaming i/o
virtual int write (const void *buffer, int nbytes)
virtual int read (void *buffer, int nbytes)
virtual void wait_for_completion ()
Public Member Functions inherited from fusb_ephandle
fusb_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle ()
int block_size ()
returns current block size.
Additional Inherited Members
Protected Attributes inherited from fusb_ephandle
int d_endpoint
bool d_input_p
int d_block_size
int d_nblocks
bool d_started
Detailed Description
win32 implementation of fusb_ephandle using libusb-win32
Constructor & Destructor Documentation
fusb_ephandle_win32::fusb_ephandle_win32 (fusb_devhandle_win32 * dh, int endpoint, bool input_p, int block_size = 0, int nblocks = 0)
References fusb_ephandle::d_block_size, fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, and fusb_devhandle::get_usb_dev_handle().
fusb_ephandle_win32::~fusb_ephandle_win32 () virtual
References fusb_ephandle::d_nblocks, and stop().
Member Function Documentation
int fusb_ephandle_win32::read (void * buffer, int nbytes) virtual
Returns
number of bytes read or -1 if error. number of bytes read will be <= nbytes. Will block if no input available.
Implements fusb_ephandle.
References fusb_ephandle::d_block_size, fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, and fusb_ephandle::d_started.
bool fusb_ephandle_win32::start () virtual
begin streaming i/o
Implements fusb_ephandle.
References fusb_ephandle::d_block_size, fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, and fusb_ephandle::d_started.
bool fusb_ephandle_win32::stop () virtual
stop streaming i/o
Implements fusb_ephandle.
References fusb_ephandle::d_input_p, fusb_ephandle::d_started, and wait_for_completion().
Referenced by ~fusb_ephandle_win32().
void fusb_ephandle_win32::wait_for_completion () virtual
Implements fusb_ephandle.
References fusb_ephandle::d_nblocks.
Referenced by stop().
int fusb_ephandle_win32::write (const void * buffer, int nbytes) virtual
Returns
nbytes if write was successfully enqueued, else -1. Will block if no free buffers available.
Implements fusb_ephandle.
References fusb_ephandle::d_block_size, fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, and fusb_ephandle::d_started.
The documentation for this class was generated from the following files:
fusb_win32.h
fusb_win32.cc