Universal Software Radio Peripheral: fusb_devhandle_linux Class Reference
fusb_devhandle_linux Class Reference
linux specific implementation of fusb_devhandle using usbdevice_fs
#include <fusb_linux.h>
Public Member Functions
fusb_devhandle_linux (usb_dev_handle *udh)
virtual ~fusb_devhandle_linux ()
virtual fusb_ephandle * make_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)
return an ephandle of the correct subtype
bool _submit_urb (usbdevfs_urb *urb)
bool _cancel_urb (usbdevfs_urb *urb)
void _cancel_pending_rqsts (fusb_ephandle_linux *eph)
bool _reap (bool ok_to_block_p)
void _wait_for_completion ()
Public Member Functions inherited from fusb_devhandle
fusb_devhandle (libusb_device_handle *udh)
virtual ~fusb_devhandle ()
libusb_device_handle * get_usb_dev_handle () const
Additional Inherited Members
Protected Attributes inherited from fusb_devhandle
libusb_device_handle * d_udh
Detailed Description
linux specific implementation of fusb_devhandle using usbdevice_fs
Constructor & Destructor Documentation
fusb_devhandle_linux::fusb_devhandle_linux (usb_dev_handle * udh)
fusb_devhandle_linux::~fusb_devhandle_linux () virtual
References _cancel_urb().
Member Function Documentation
void fusb_devhandle_linux::_cancel_pending_rqsts (fusb_ephandle_linux * eph)
References _cancel_urb().
Referenced by fusb_ephandle_linux::stop().
bool fusb_devhandle_linux::_cancel_urb (usbdevfs_urb * urb)
References fusb_devhandle::d_udh.
Referenced by _cancel_pending_rqsts(), and ~fusb_devhandle_linux().
bool fusb_devhandle_linux::_reap (bool ok_to_block_p)
References fusb_ephandle_linux::completed_list_add(), and fusb_devhandle::d_udh.
Referenced by _wait_for_completion(), fusb_ephandle_linux::read(), fusb_ephandle_linux::stop(), and fusb_ephandle_linux::write().
bool fusb_devhandle_linux::_submit_urb (usbdevfs_urb * urb)
References fusb_devhandle::d_udh.
Referenced by fusb_ephandle_linux::completed_list_get().
void fusb_devhandle_linux::_wait_for_completion ()
References _reap().
Referenced by fusb_ephandle_linux::wait_for_completion().
fusb_ephandle * fusb_devhandle_linux::make_ephandle (int endpoint, bool input_p, int block_size = 0, int nblocks = 0) virtual
return an ephandle of the correct subtype
Implements fusb_devhandle.
The documentation for this class was generated from the following files:
fusb_linux.h
fusb_linux.cc