Universal Software Radio Peripheral: db_dtt754 Class Reference
db_dtt754 Class Reference
#include <db_dtt754.h>
Public Member Functions
db_dtt754 (usrp_basic_sptr usrp, int which)
~db_dtt754 ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
bool set_gain (float gain)
double freq_min ()
double freq_max ()
struct freq_result_t set_freq (double target_freq)
bool is_quadrature ()
bool spectrum_inverted ()
bool set_bw (float bw)
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool i_and_q_swapped ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
Additional Inherited Members
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
virtual int _refclk_divisor ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_dtt754::db_dtt754 (usrp_basic_sptr usrp, int which)
References db_base::bypass_adc_buffers(), db_base::d_which, gain_max(), gain_min(), and set_gain().
db_dtt754::~db_dtt754 ()
Member Function Documentation
double db_dtt754::freq_max () virtual
Implements db_base.
Referenced by set_freq().
double db_dtt754::freq_min () virtual
Implements db_base.
Referenced by set_freq().
float db_dtt754::gain_db_per_step () virtual
Implements db_base.
float db_dtt754::gain_max () virtual
Implements db_base.
Referenced by db_dtt754().
float db_dtt754::gain_min () virtual
Implements db_base.
Referenced by db_dtt754().
bool db_dtt754::is_quadrature () virtual
Implements db_base.
bool db_dtt754::set_bw (float bw) virtual
Reimplemented from db_base.
References db_base::d_which, set_freq(), usrp_basic::set_pga(), db_base::usrp(), and usrp_basic::write_aux_dac().
struct freq_result_t db_dtt754::set_freq (double target_freq) virtual
Implements db_base.
References bandswitch_byte(), control_byte_1(), control_byte_2(), freq_max(), freq_min(), int_seq_to_str(), db_base::usrp(), and usrp_basic::write_i2c().
Referenced by set_bw().
bool db_dtt754::set_gain (float gain) virtual
Implements db_base.
Referenced by db_dtt754().
bool db_dtt754::spectrum_inverted () virtual
Reimplemented from db_base.
The documentation for this class was generated from the following files:
db_dtt754.h
db_dtt754.cc