Universal Software Radio Peripheral: dxc_control Class Reference
dxc_control Class Reference abstract
Public Member Functions
virtual bool is_tx ()=0
virtual bool set_dxc_freq (double dxc_freq)=0
virtual double dxc_freq ()=0
Member Function Documentation
virtual double dxc_control::dxc_freq () pure virtual
Implemented in duc_control, and ddc_control.
Referenced by duc_control::dxc_freq().
virtual bool dxc_control::is_tx () pure virtual
Implemented in duc_control, and ddc_control.
Referenced by duc_control::dxc_freq().
virtual bool dxc_control::set_dxc_freq (double dxc_freq) pure virtual
Implemented in duc_control, and ddc_control.
Referenced by duc_control::dxc_freq().
The documentation for this class was generated from the following file:
usrp_standard.cc