Universal Software Radio Peripheral: db_wbxng_rx Class Reference
db_wbxng_rx Class Reference
#include <db_wbxng.h>
Public Member Functions
db_wbxng_rx (usrp_basic_sptr usrp, int which)
~db_wbxng_rx ()
bool set_auto_tr (bool on)
bool select_rx_antenna (int which_antenna)
bool select_rx_antenna (const std::string &which_antenna)
bool set_gain (float gain)
float gain_min ()
float gain_max ()
float gain_db_per_step ()
bool i_and_q_swapped ()
Public Member Functions inherited from wbxng_base
wbxng_base (usrp_basic_sptr usrp, int which)
~wbxng_base ()
struct freq_result_t set_freq (double freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_bw (float bw)
Protected Member Functions
void shutdown ()
bool _set_attn (float attn)
Protected Member Functions inherited from wbxng_base
void _write_spi (std::string data)
int _refclk_divisor ()
bool _get_locked ()
bool _set_pga (float pga_gain)
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
Additional Inherited Members
Protected Attributes inherited from wbxng_base
bool d_first
int d_spi_format
int d_spi_enable
int d_power_on
int d_PD
boost::shared_ptr< adf4350 > d_common
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_wbxng_rx::db_wbxng_rx (usrp_basic_sptr usrp, int which)
References usrp_basic::_write_oe(), wbxng_base::_write_spi(), ATTN_MASK, db_base::bypass_adc_buffers(), wbxng_base::d_common, wbxng_base::d_spi_enable, db_base::d_which, ENABLE_33, ENABLE_5, gain_min(), PLL_CE, PLL_PDBRF, RX2_RX1N, RXBB_EN, select_rx_antenna(), set_gain(), db_base::usrp(), and usrp_basic::write_io().
db_wbxng_rx::~db_wbxng_rx ()
References shutdown().
Member Function Documentation
bool db_wbxng_rx::_set_attn (float attn) protected
References ATTN_MASK, ATTN_SHIFT, db_base::d_which, db_base::usrp(), and usrp_basic::write_io().
Referenced by set_gain().
float db_wbxng_rx::gain_db_per_step () virtual
Implements db_base.
float db_wbxng_rx::gain_max () virtual
Implements db_base.
References usrp_basic::pga_max(), and db_base::usrp().
Referenced by set_gain().
float db_wbxng_rx::gain_min () virtual
Implements db_base.
References usrp_basic::pga_min(), and db_base::usrp().
Referenced by db_wbxng_rx(), and set_gain().
bool db_wbxng_rx::i_and_q_swapped () virtual
Reimplemented from db_base.
bool db_wbxng_rx::select_rx_antenna (int which_antenna) virtual
Reimplemented from db_base.
References db_base::d_which, RX2_RX1N, db_base::usrp(), and usrp_basic::write_io().
Referenced by db_wbxng_rx().
bool db_wbxng_rx::select_rx_antenna (const std::string & which_antenna) virtual
Reimplemented from db_base.
References db_base::d_which, RX2_RX1N, db_base::usrp(), and usrp_basic::write_io().
bool db_wbxng_rx::set_auto_tr (bool on) virtual
Reimplemented from db_base.
References freq_result_t::ok, RX2_RX1N, RXBB_EN, db_base::set_atr_mask(), db_base::set_atr_rxval(), and db_base::set_atr_txval().
Referenced by shutdown().
bool db_wbxng_rx::set_gain (float gain) virtual
Implements db_base.
References _set_attn(), wbxng_base::_set_pga(), gain_max(), gain_min(), usrp_basic::pga_max(), and db_base::usrp().
Referenced by db_wbxng_rx().
void db_wbxng_rx::shutdown () protected virtual
Called to shutdown daughterboard. Called from dtor and usrp_basic dtor.
N.B., any class that overrides shutdown MUST call shutdown in its destructor.
Reimplemented from db_base.
References db_base::_enable_refclk(), ATTN_MASK, db_base::d_is_shutdown, db_base::d_which, ENABLE_33, ENABLE_5, PLL_CE, PLL_PDBRF, RX2_RX1N, RXBB_EN, set_auto_tr(), db_base::usrp(), and usrp_basic::write_io().
Referenced by ~db_wbxng_rx().
The documentation for this class was generated from the following files:
db_wbxng.h
db_wbxng.cc