Universal Software Radio Peripheral: db_dbs_rx Class Reference
db_dbs_rx Class Reference
#include <db_dbs_rx.h>
Public Member Functions
db_dbs_rx (usrp_basic_sptr usrp, int which)
~db_dbs_rx ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
double freq_min ()
double freq_max ()
struct freq_result_t set_freq (double freq)
bool set_gain (float gain)
bool is_quadrature ()
bool set_bw (float bw)
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
Protected Member Functions
void shutdown ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
Additional Inherited Members
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_dbs_rx::db_dbs_rx (usrp_basic_sptr usrp, int which)
References db_base::_enable_refclk(), usrp_basic::_write_oe(), db_base::bypass_adc_buffers(), db_base::d_which, gain_max(), gain_min(), set_gain(), and db_base::usrp().
db_dbs_rx::~db_dbs_rx ()
References shutdown().
Member Function Documentation
double db_dbs_rx::freq_max () virtual
Implements db_base.
Referenced by set_freq().
double db_dbs_rx::freq_min () virtual
Implements db_base.
Referenced by set_freq().
float db_dbs_rx::gain_db_per_step () virtual
Implements db_base.
float db_dbs_rx::gain_max () virtual
Implements db_base.
Referenced by db_dbs_rx().
float db_dbs_rx::gain_min () virtual
Implements db_base.
Referenced by db_dbs_rx().
bool db_dbs_rx::is_quadrature () virtual
Implements db_base.
bool db_dbs_rx::set_bw (float bw) virtual
Reimplemented from db_base.
References db_base::_refclk_freq(), db_base::d_which, usrp_basic::set_pga(), db_base::usrp(), and usrp_basic::write_aux_dac().
struct freq_result_t db_dbs_rx::set_freq (double freq) virtual
Implements db_base.
References db_base::_refclk_freq(), freq_max(), and freq_min().
bool db_dbs_rx::set_gain (float gain) virtual
Implements db_base.
Referenced by db_dbs_rx().
void db_dbs_rx::shutdown () protected virtual
Called to shutdown daughterboard. Called from dtor and usrp_basic dtor.
N.B., any class that overrides shutdown MUST call shutdown in its destructor.
Reimplemented from db_base.
References db_base::_enable_refclk(), db_base::d_is_shutdown, int_seq_to_str(), usrp_basic::read_i2c(), str_to_int_seq(), db_base::usrp(), and usrp_basic::write_i2c().
Referenced by ~db_dbs_rx().
The documentation for this class was generated from the following files:
db_dbs_rx.h
db_dbs_rx.cc