Universal Software Radio Peripheral: s_buffer Class Reference
s_buffer Class Reference
#include <fusb_darwin.h>
Public Member Functions
s_buffer (size_t n_alloc=0)
~s_buffer ()
size_t n_used ()
void n_used (size_t bufLen)
size_t n_alloc ()
void buffer (char *l_buffer, size_t bufLen)
char * buffer ()
void reset ()
Constructor & Destructor Documentation
s_buffer::s_buffer (size_t n_alloc = 0) inline
s_buffer::~s_buffer () inline
Member Function Documentation
void s_buffer::buffer (char * l_buffer, size_t bufLen) inline
Referenced by fusb_ephandle_darwin::start(), and fusb_ephandle_darwin::write().
char* s_buffer::buffer () inline
size_t s_buffer::n_alloc () inline
size_t s_buffer::n_used () inline
Referenced by fusb_ephandle_darwin::start(), and fusb_ephandle_darwin::write().
void s_buffer::n_used (size_t bufLen) inline
void s_buffer::reset () inline
Referenced by fusb_ephandle_darwin::start().
The documentation for this class was generated from the following file:
fusb_darwin.h