Universal Software Radio Peripheral: db_xcvr2450_tx Class Reference
db_xcvr2450_tx Class Reference
#include <db_xcvr2450.h>
Public Member Functions
db_xcvr2450_tx (usrp_basic_sptr usrp, int which)
~db_xcvr2450_tx ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
bool set_gain (float gain)
bool i_and_q_swapped ()
Public Member Functions inherited from db_xcvr2450_base
db_xcvr2450_base (usrp_basic_sptr usrp, int which)
~db_xcvr2450_base ()
struct freq_result_t set_freq (double target_freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Protected Member Functions
void shutdown ()
Protected Member Functions inherited from db_xcvr2450_base
void shutdown_common ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
virtual int _refclk_divisor ()
usrp_basic * usrp ()
Additional Inherited Members
Protected Attributes inherited from db_xcvr2450_base
xcvr2450_sptr d_xcvr
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_xcvr2450_tx::db_xcvr2450_tx (usrp_basic_sptr usrp, int which)
References LO_OFFSET, and db_base::set_lo_offset().
db_xcvr2450_tx::~db_xcvr2450_tx ()
References shutdown().
Member Function Documentation
float db_xcvr2450_tx::gain_db_per_step () virtual
Implements db_base.
float db_xcvr2450_tx::gain_max () virtual
Implements db_base.
float db_xcvr2450_tx::gain_min () virtual
Implements db_base.
bool db_xcvr2450_tx::i_and_q_swapped () virtual
Reimplemented from db_base.
bool db_xcvr2450_tx::set_gain (float gain) virtual
Implements db_base.
References db_xcvr2450_base::d_xcvr.
void db_xcvr2450_tx::shutdown () protected virtual
Called to shutdown daughterboard. Called from dtor and usrp_basic dtor.
N.B., any class that overrides shutdown MUST call shutdown in its destructor.
Reimplemented from db_base.
References db_base::d_is_shutdown, and db_xcvr2450_base::shutdown_common().
Referenced by ~db_xcvr2450_tx().
The documentation for this class was generated from the following files:
db_xcvr2450.h
db_xcvr2450.cc