Universal Software Radio Peripheral: fusb_ephandle_libusb1 Class Reference
fusb_ephandle_libusb1 Class Reference
libusb1 implementation of fusb_ephandle
#include <fusb_libusb1.h>
Public Member Functions
fusb_ephandle_libusb1 (fusb_devhandle_libusb1 *dh, int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle_libusb1 ()
virtual bool start ()
begin streaming i/o
virtual bool stop ()
stop streaming i/o
virtual int write (const void *buffer, int nbytes)
virtual int read (void *buffer, int nbytes)
virtual void wait_for_completion ()
void free_list_add (struct libusb_transfer *lut)
void completed_list_add (struct libusb_transfer *lut)
struct libusb_transfer * free_list_get ()
struct libusb_transfer * completed_list_get ()
fusb_devhandle_libusb1 * get_fusb_devhandle_libusb1 () const
Public Member Functions inherited from fusb_ephandle
fusb_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle ()
int block_size ()
returns current block size.
Additional Inherited Members
Protected Attributes inherited from fusb_ephandle
int d_endpoint
bool d_input_p
int d_block_size
int d_nblocks
bool d_started
Detailed Description
libusb1 implementation of fusb_ephandle
Constructor & Destructor Documentation
fusb_ephandle_libusb1::fusb_ephandle_libusb1 (fusb_devhandle_libusb1 * dh, int endpoint, bool input_p, int block_size = 0, int nblocks = 0)
References fusb_ephandle::d_block_size, fusb_ephandle::d_endpoint, fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, and MINIMIZE_TX_BUFFERING.
fusb_ephandle_libusb1::~fusb_ephandle_libusb1 () virtual
References completed_list_get(), free_list_get(), and stop().
Member Function Documentation
void fusb_ephandle_libusb1::completed_list_add (struct libusb_transfer * lut)
libusb_transfer * fusb_ephandle_libusb1::completed_list_get ()
References fusb_devhandle_libusb1::_submit_lut(), and free_list_add().
Referenced by read(), stop(), write(), and ~fusb_ephandle_libusb1().
void fusb_ephandle_libusb1::free_list_add (struct libusb_transfer * lut)
Referenced by completed_list_get(), read(), stop(), and write().
libusb_transfer * fusb_ephandle_libusb1::free_list_get ()
Referenced by start(), write(), and ~fusb_ephandle_libusb1().
fusb_devhandle_libusb1* fusb_ephandle_libusb1::get_fusb_devhandle_libusb1 () const inline
int fusb_ephandle_libusb1::read (void * buffer, int nbytes) virtual
Returns
number of bytes read or -1 if error. number of bytes read will be <= nbytes. Will block if no input available.
Implements fusb_ephandle.
References fusb_devhandle_libusb1::_reap(), completed_list_get(), fusb_ephandle::d_input_p, fusb_ephandle::d_started, and free_list_add().
bool fusb_ephandle_libusb1::start () virtual
begin streaming i/o
Implements fusb_ephandle.
References fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, fusb_ephandle::d_started, and free_list_get().
bool fusb_ephandle_libusb1::stop () virtual
stop streaming i/o
Implements fusb_ephandle.
References fusb_devhandle_libusb1::_cancel_pending_rqsts(), fusb_devhandle_libusb1::_reap(), completed_list_get(), fusb_ephandle::d_input_p, fusb_ephandle::d_nblocks, fusb_ephandle::d_started, free_list_add(), and write().
Referenced by ~fusb_ephandle_libusb1().
void fusb_ephandle_libusb1::wait_for_completion () virtual
Implements fusb_ephandle.
References fusb_devhandle_libusb1::_wait_for_completion().
int fusb_ephandle_libusb1::write (const void * buffer, int nbytes) virtual
Returns
nbytes if write was successfully enqueued, else -1. Will block if no free buffers available.
Implements fusb_ephandle.
References fusb_devhandle_libusb1::_reap(), completed_list_get(), fusb_ephandle::d_input_p, fusb_ephandle::d_started, free_list_add(), and free_list_get().
Referenced by stop().
The documentation for this class was generated from the following files:
fusb_libusb1.h
fusb_libusb1.cc