Universal Software Radio Peripheral: fusb_ephandle_darwin Class Reference
fusb_ephandle_darwin Class Reference
darwin implementation of fusb_ephandle
#include <fusb_darwin.h>
Public Member Functions
fusb_ephandle_darwin (fusb_devhandle_darwin *dh, int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle_darwin ()
virtual bool start ()
begin streaming i/o
virtual bool stop ()
stop streaming i/o
virtual int write (const void *buffer, int nbytes)
virtual int read (void *buffer, int nbytes)
void abort ()
virtual void wait_for_completion ()
Public Member Functions inherited from fusb_ephandle
fusb_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)
virtual ~fusb_ephandle ()
int block_size ()
returns current block size.
Public Attributes
UInt8 d_pipeRef
UInt8 d_transferType
usb_interface_t ** d_interfaceRef
usb_interface_t * d_interface
s_queue_ptr d_queue
circular_buffer< char > * d_buffer
size_t d_bufLenBytes
gruel::mutex * d_readRunning
gruel::mutex * d_runBlock_mutex
gruel::mutex * d_readBlock_mutex
gruel::condition_variable * d_runBlock
gruel::condition_variable * d_readBlock
Additional Inherited Members
Protected Attributes inherited from fusb_ephandle
int d_endpoint
bool d_input_p
int d_block_size
int d_nblocks
bool d_started
Detailed Description
darwin implementation of fusb_ephandle
This is currently identical to the generic implementation and is intended as a starting point for whatever magic is required to make usb fly.
Constructor & Destructor Documentation
fusb_ephandle_darwin::fusb_ephandle_darwin (fusb_devhandle_darwin * dh, int endpoint, bool input_p, int block_size = 0, int nblocks = 0)
References s_node< T >::both(), d_buffer, d_bufLenBytes, fusb_ephandle::d_input_p, d_queue, d_readBlock, d_readBlock_mutex, d_readRunning, d_runBlock, d_runBlock_mutex, fusb_sysconfig::max_block_size(), and s_node< T >::object().
fusb_ephandle_darwin::~fusb_ephandle_darwin () virtual
References s_node< T >::both(), d_buffer, d_queue, d_readBlock, d_readBlock_mutex, d_readRunning, d_runBlock, d_runBlock_mutex, circular_linked_list< T >::iterate_next(), circular_linked_list< T >::iterate_start(), s_node< T >::object(), and stop().
Member Function Documentation
void fusb_ephandle_darwin::abort ()
References d_interface, d_interfaceRef, d_pipeRef, usb_debug, and USB_ERROR_STR_NO_RET.
Referenced by stop().
int fusb_ephandle_darwin::read (void * buffer, int nbytes) virtual
Returns
number of bytes read or -1 if error. number of bytes read will be <= nbytes. Will block if no input available.
Implements fusb_ephandle.
References d_buffer, circular_buffer< T >::dequeue(), and usb_debug.
bool fusb_ephandle_darwin::start () virtual
begin streaming i/o
Implements fusb_ephandle.
References s_node< T >::both(), s_buffer::buffer(), d_buffer, d_bufLenBytes, fusb_ephandle::d_endpoint, fusb_ephandle::d_input_p, d_interface, d_interfaceRef, d_pipeRef, d_queue, d_readBlock, d_readBlock_mutex, d_readRunning, d_runBlock, d_runBlock_mutex, fusb_ephandle::d_started, d_transferType, circular_buffer< T >::enqueue(), fusb_devhandle::get_usb_dev_handle(), usb_dev_handle::impl_info, darwin_dev_handle::interface, circular_linked_list< T >::iterate_next(), circular_linked_list< T >::iterate_start(), s_buffer::n_used(), s_both< T >::node(), circular_linked_list< T >::num_used(), s_node< T >::object(), s_buffer::reset(), circular_buffer< T >::reset(), s_both< T >::set(), s_node< T >::set_available(), s_both< T >::This(), usb_debug, USB_ERROR_STR, USB_ERROR_STR_NO_RET, and usb_interface_t.
bool fusb_ephandle_darwin::stop () virtual
stop streaming i/o
Implements fusb_ephandle.
References abort(), circular_buffer< T >::abort(), d_buffer, fusb_ephandle::d_input_p, fusb_ephandle::d_started, usb_debug, and wait_for_completion().
Referenced by ~fusb_ephandle_darwin().
void fusb_ephandle_darwin::wait_for_completion () virtual
Implements fusb_ephandle.
References d_queue, and circular_linked_list< T >::in_use().
Referenced by stop().
int fusb_ephandle_darwin::write (const void * buffer, int nbytes) virtual
Returns
nbytes if write was successfully enqueued, else -1. Will block if no free buffers available.
Implements fusb_ephandle.
References s_node< T >::both(), s_buffer::buffer(), d_bufLenBytes, d_interface, d_interfaceRef, d_pipeRef, d_queue, fusb_ephandle::d_started, d_transferType, circular_linked_list< T >::find_next_available_node(), circular_linked_list< T >::make_node_available(), s_buffer::n_used(), s_both< T >::node(), s_node< T >::object(), s_both< T >::This(), usb_debug, and USB_ERROR_STR.
Member Data Documentation
circular_buffer<char>* fusb_ephandle_darwin::d_buffer
Referenced by fusb_ephandle_darwin(), read(), start(), stop(), and ~fusb_ephandle_darwin().
size_t fusb_ephandle_darwin::d_bufLenBytes
Referenced by fusb_ephandle_darwin(), start(), and write().
usb_interface_t* fusb_ephandle_darwin::d_interface
Referenced by abort(), start(), and write().
usb_interface_t** fusb_ephandle_darwin::d_interfaceRef
Referenced by abort(), start(), and write().
UInt8 fusb_ephandle_darwin::d_pipeRef
Referenced by abort(), start(), and write().
s_queue_ptr fusb_ephandle_darwin::d_queue
Referenced by fusb_ephandle_darwin(), start(), wait_for_completion(), write(), and ~fusb_ephandle_darwin().
gruel::condition_variable* fusb_ephandle_darwin::d_readBlock
Referenced by fusb_ephandle_darwin(), start(), and ~fusb_ephandle_darwin().
gruel::mutex* fusb_ephandle_darwin::d_readBlock_mutex
Referenced by fusb_ephandle_darwin(), start(), and ~fusb_ephandle_darwin().
gruel::mutex* fusb_ephandle_darwin::d_readRunning
Referenced by fusb_ephandle_darwin(), start(), and ~fusb_ephandle_darwin().
gruel::condition_variable* fusb_ephandle_darwin::d_runBlock
Referenced by fusb_ephandle_darwin(), start(), and ~fusb_ephandle_darwin().
gruel::mutex* fusb_ephandle_darwin::d_runBlock_mutex
Referenced by fusb_ephandle_darwin(), start(), and ~fusb_ephandle_darwin().
UInt8 fusb_ephandle_darwin::d_transferType
Referenced by start(), and write().
The documentation for this class was generated from the following files:
fusb_darwin.h
fusb_darwin.cc