Universal Software Radio Peripheral: s_both< T > Class Template Reference
s_both< T > Class Template Reference
#include <circular_linked_list.h>
Public Member Functions
__INLINE__ s_both (s_node< T > *l_node, void *l_this)
__INLINE__ ~s_both ()
__INLINE__ s_node< T > * node ()
__INLINE__ void * This ()
__INLINE__ void set (s_node< T > *l_node, void *l_this)
Constructor & Destructor Documentation
template<class T> __INLINE__ s_both< T >::s_both (s_node< T > * l_node, void * l_this) inline
template<class T> __INLINE__ s_both< T >::~s_both () inline
Member Function Documentation
template<class T> __INLINE__ s_node<T>* s_both< T >::node () inline
Referenced by fusb_ephandle_darwin::start(), and fusb_ephandle_darwin::write().
template<class T> __INLINE__ void s_both< T >::set (s_node< T > * l_node, void * l_this) inline
Referenced by fusb_ephandle_darwin::start().
template<class T> __INLINE__ void* s_both< T >::This () inline
Referenced by fusb_ephandle_darwin::start(), and fusb_ephandle_darwin::write().
The documentation for this class was generated from the following file:
circular_linked_list.h