Universal Software Radio Peripheral: usrp_standard_common Class Reference
usrp_standard_common Class Reference
#include <usrp_standard.h>
Public Member Functions
bool has_rx_halfband () const
does the FPGA implement the final Rx half-band filter? If it doesn't, the maximum decimation factor with proper gain is 1/2 of what it would otherwise be.
int nddcs () const
number of digital downconverters implemented in the FPGA This will be 0, 1, 2 or 4.
bool has_tx_halfband () const
does the FPGA implement the initial Tx half-band filter?
int nducs () const
number of digital upconverters implemented in the FPGA This will be 0, 1, or 2.
Static Public Member Functions
static void calc_dxc_freq (double target_freq, double baseband_freq, double fs, double *dxc_freq, bool *inverted)
Calculate the frequency to use for setting the digital up or down converter.
Protected Member Functions
usrp_standard_common (usrp_basic *parent)
Constructor & Destructor Documentation
usrp_standard_common::usrp_standard_common (usrp_basic * parent) protected
References usrp_basic::_read_fpga_reg().
Member Function Documentation
void usrp_standard_common::calc_dxc_freq (double target_freq, double baseband_freq, double fs, double * dxc_freq, bool * inverted) static
Calculate the frequency to use for setting the digital up or down converter.
Parameters
target_freq is the desired RF frequency (Hz).
baseband_freq is the RF frequency that corresponds to DC in the IF coming from the d'board.
fs is the sampling frequency.
[out] dxc_freq the frequency to program into the DDC (or DUC).
[out] inverted is true if we're operating in an inverted Nyquist zone.
Referenced by duc_control::dxc_freq().
bool usrp_standard_common::has_rx_halfband () const
does the FPGA implement the final Rx half-band filter? If it doesn't, the maximum decimation factor with proper gain is 1/2 of what it would otherwise be.
Referenced by usrp_standard_rx::set_decim_rate().
bool usrp_standard_common::has_tx_halfband () const
does the FPGA implement the initial Tx half-band filter?
int usrp_standard_common::nddcs () const
number of digital downconverters implemented in the FPGA This will be 0, 1, 2 or 4.
Referenced by usrp_standard_rx::set_nchannels().
int usrp_standard_common::nducs () const
number of digital upconverters implemented in the FPGA This will be 0, 1, or 2.
Referenced by usrp_standard_tx::set_nchannels().
The documentation for this class was generated from the following files:
usrp_standard.h
usrp_standard.cc