Universal Software Radio Peripheral: xcvr2450 Class Reference
xcvr2450 Class Reference
Public Member Functions
usrp_basic * usrp ()
xcvr2450 (usrp_basic_sptr usrp, int which)
~xcvr2450 ()
void shutdown ()
void set_reg_standby ()
void set_reg_int_divider ()
void set_reg_frac_divider ()
void set_reg_bandselpll ()
void set_reg_cal ()
void set_reg_lpf ()
void set_reg_rxrssi_ctrl ()
void set_reg_txlin_gain ()
void set_reg_pabias ()
void set_reg_rxgain ()
void set_reg_txgain ()
void send_reg (int v)
void set_gpio ()
bool lock_detect ()
bool set_rx_gain (float gain)
bool set_tx_gain (float gain)
struct freq_result_t set_freq (double target_freq)
Constructor & Destructor Documentation
xcvr2450::xcvr2450 (usrp_basic_sptr usrp, int which)
References usrp_basic::_common_write_oe(), C_RX, C_TX, usrp_basic::common_write_atr_mask(), usrp_basic::common_write_atr_rxval(), usrp_basic::common_write_atr_txval(), usrp_basic::common_write_io(), RX_OE_MASK, RX_SAFE_IO, set_reg_bandselpll(), set_reg_cal(), set_reg_lpf(), set_reg_pabias(), set_reg_rxgain(), set_reg_rxrssi_ctrl(), set_reg_standby(), set_reg_txgain(), set_reg_txlin_gain(), TX_OE_MASK, TX_SAFE_IO, and usrp().
xcvr2450::~xcvr2450 ()
References shutdown().
Member Function Documentation
bool xcvr2450::lock_detect ()
References C_RX, LOCKDET, and usrp().
Referenced by set_freq().
void xcvr2450::send_reg (int v)
References usrp_basic::_write_spi(), and usrp().
Referenced by set_reg_bandselpll(), set_reg_cal(), set_reg_frac_divider(), set_reg_int_divider(), set_reg_lpf(), set_reg_pabias(), set_reg_rxgain(), set_reg_rxrssi_ctrl(), set_reg_standby(), set_reg_txgain(), and set_reg_txlin_gain().
struct freq_result_t xcvr2450::set_freq (double target_freq)
References freq_result_t::baseband_freq, usrp_basic::fpga_master_clock_freq(), lock_detect(), freq_result_t::ok, set_gpio(), set_reg_bandselpll(), set_reg_frac_divider(), set_reg_int_divider(), and usrp().
void xcvr2450::set_gpio ()
References usrp_basic::_common_write_oe(), AD9515DIV, ANTSEL_TX1_RX2, ANTSEL_TX2_RX1, C_RX, C_TX, usrp_basic::common_write_atr_mask(), usrp_basic::common_write_atr_rxval(), usrp_basic::common_write_atr_txval(), usrp_basic::common_write_io(), EN, HB_PA_OFF, LB_PA_OFF, RX_EN, RX_HP, RX_OE_MASK, RX_SAFE_IO, TX_EN, TX_OE_MASK, TX_SAFE_IO, and usrp().
Referenced by set_freq().
void xcvr2450::set_reg_bandselpll ()
References send_reg().
Referenced by set_freq(), and xcvr2450().
void xcvr2450::set_reg_cal ()
References send_reg().
Referenced by xcvr2450().
void xcvr2450::set_reg_frac_divider ()
References send_reg().
Referenced by set_freq().
void xcvr2450::set_reg_int_divider ()
References send_reg().
Referenced by set_freq().
void xcvr2450::set_reg_lpf ()
References send_reg().
Referenced by xcvr2450().
void xcvr2450::set_reg_pabias ()
References send_reg().
Referenced by xcvr2450().
void xcvr2450::set_reg_rxgain ()
References send_reg().
Referenced by set_rx_gain(), and xcvr2450().
void xcvr2450::set_reg_rxrssi_ctrl ()
References send_reg().
Referenced by xcvr2450().
void xcvr2450::set_reg_standby ()
References send_reg().
Referenced by xcvr2450().
void xcvr2450::set_reg_txgain ()
References send_reg().
Referenced by set_tx_gain(), and xcvr2450().
void xcvr2450::set_reg_txlin_gain ()
References send_reg().
Referenced by xcvr2450().
bool xcvr2450::set_rx_gain (float gain)
References set_reg_rxgain().
bool xcvr2450::set_tx_gain (float gain)
References set_reg_txgain().
void xcvr2450::shutdown ()
References C_RX, C_TX, usrp_basic::common_write_atr_rxval(), usrp_basic::common_write_atr_txval(), RX_SAFE_IO, TX_SAFE_IO, and usrp().
Referenced by ~xcvr2450().
usrp_basic* xcvr2450::usrp () inline
References xcvr2450_key::which.
Referenced by lock_detect(), send_reg(), set_freq(), set_gpio(), shutdown(), and xcvr2450().
The documentation for this class was generated from the following file:
db_xcvr2450.cc