Universal Software Radio Peripheral: fusb_devhandle_libusb1 Class Reference
fusb_devhandle_libusb1 Class Reference
libusb1 implementation of fusb_devhandle
#include <fusb_libusb1.h>
Public Member Functions
fusb_devhandle_libusb1 (libusb_device_handle *udh, libusb_context *ctx)
virtual ~fusb_devhandle_libusb1 ()
virtual fusb_ephandle * make_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)
return an ephandle of the correct subtype
bool _submit_lut (libusb_transfer *)
bool _cancel_lut (libusb_transfer *)
void _cancel_pending_rqsts (fusb_ephandle_libusb1 *eph)
bool _reap (bool ok_to_block_p)
void _wait_for_completion ()
bool pending_remove (struct libusb_transfer *lut)
bool _teardown ()
Public Member Functions inherited from fusb_devhandle
fusb_devhandle (libusb_device_handle *udh)
virtual ~fusb_devhandle ()
libusb_device_handle * get_usb_dev_handle () const
Additional Inherited Members
Protected Attributes inherited from fusb_devhandle
libusb_device_handle * d_udh
Detailed Description
libusb1 implementation of fusb_devhandle
Constructor & Destructor Documentation
fusb_devhandle_libusb1::fusb_devhandle_libusb1 (libusb_device_handle * udh, libusb_context * ctx)
fusb_devhandle_libusb1::~fusb_devhandle_libusb1 () virtual
References _cancel_lut(), and _wait_for_completion().
Member Function Documentation
bool fusb_devhandle_libusb1::_cancel_lut (libusb_transfer * lut)
Referenced by _cancel_pending_rqsts(), and ~fusb_devhandle_libusb1().
void fusb_devhandle_libusb1::_cancel_pending_rqsts (fusb_ephandle_libusb1 * eph)
References _cancel_lut().
Referenced by fusb_ephandle_libusb1::stop().
bool fusb_devhandle_libusb1::_reap (bool ok_to_block_p)
Referenced by _wait_for_completion(), fusb_ephandle_libusb1::read(), fusb_ephandle_libusb1::stop(), and fusb_ephandle_libusb1::write().
bool fusb_devhandle_libusb1::_submit_lut (libusb_transfer * lut)
Referenced by fusb_ephandle_libusb1::completed_list_get().
bool fusb_devhandle_libusb1::_teardown () inline
void fusb_devhandle_libusb1::_wait_for_completion ()
References _reap().
Referenced by fusb_ephandle_libusb1::wait_for_completion(), and ~fusb_devhandle_libusb1().
fusb_ephandle * fusb_devhandle_libusb1::make_ephandle (int endpoint, bool input_p, int block_size = 0, int nblocks = 0) virtual
return an ephandle of the correct subtype
Implements fusb_devhandle.
bool fusb_devhandle_libusb1::pending_remove (struct libusb_transfer * lut)
The documentation for this class was generated from the following files:
fusb_libusb1.h
fusb_libusb1.cc