Universal Software Radio Peripheral: wbxng_base Class Reference
wbxng_base Class Reference
#include <db_wbxng.h>
Public Member Functions
wbxng_base (usrp_basic_sptr usrp, int which)
~wbxng_base ()
struct freq_result_t set_freq (double freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual float gain_min ()=0
virtual float gain_max ()=0
virtual float gain_db_per_step ()=0
virtual bool set_gain (float gain)=0
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Protected Member Functions
void _write_spi (std::string data)
int _refclk_divisor ()
bool _get_locked ()
bool _set_pga (float pga_gain)
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes
bool d_first
int d_spi_format
int d_spi_enable
int d_power_on
int d_PD
boost::shared_ptr< adf4350 > d_common
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
wbxng_base::wbxng_base (usrp_basic_sptr usrp, int which)
References db_base::_enable_refclk(), usrp_basic::_write_oe(), d_first, d_spi_format, db_base::d_which, db_base::set_auto_tr(), and db_base::usrp().
wbxng_base::~wbxng_base ()
Member Function Documentation
bool wbxng_base::_get_locked (void) protected
References db_base::d_which, PLL_LOCK_DETECT, usrp_basic::read_io(), and db_base::usrp().
int wbxng_base::_refclk_divisor () protected virtual
Reimplemented from db_base.
bool wbxng_base::_set_pga (float pga_gain) protected
References db_base::d_which, usrp_basic::set_pga(), and db_base::usrp().
Referenced by db_wbxng_tx::set_gain(), and db_wbxng_rx::set_gain().
void wbxng_base::_write_spi (std::string data) protected
References usrp_basic::_write_spi(), d_spi_enable, d_spi_format, and db_base::usrp().
Referenced by db_wbxng_rx::db_wbxng_rx(), db_wbxng_tx::db_wbxng_tx(), and set_freq().
double wbxng_base::freq_max () virtual
Implements db_base.
References d_common.
Referenced by set_freq().
double wbxng_base::freq_min () virtual
Implements db_base.
References d_common.
Referenced by set_freq().
bool wbxng_base::is_quadrature () virtual
Implements db_base.
struct freq_result_t wbxng_base::set_freq (double freq) virtual
Implements db_base.
References db_base::_refclk_freq(), _write_spi(), d_common, freq_max(), freq_min(), and freq_result_t::ok.
Member Data Documentation
boost::shared_ptr<adf4350> wbxng_base::d_common protected
Referenced by db_wbxng_rx::db_wbxng_rx(), db_wbxng_tx::db_wbxng_tx(), freq_max(), freq_min(), and set_freq().
bool wbxng_base::d_first protected
Referenced by wbxng_base().
int wbxng_base::d_PD protected
int wbxng_base::d_power_on protected
int wbxng_base::d_spi_enable protected
Referenced by _write_spi(), db_wbxng_rx::db_wbxng_rx(), and db_wbxng_tx::db_wbxng_tx().
int wbxng_base::d_spi_format protected
Referenced by _write_spi(), and wbxng_base().
The documentation for this class was generated from the following files:
db_wbxng.h
db_wbxng.cc