Universal Software Radio Peripheral: usrp_standard_tx Class Reference
usrp_standard_tx Class Reference
The C++ interface the transmit side of the USRPThis is the recommended interface to USRP transmit functionality for applications that use the USRP but not GNU Radio.
#include <usrp_standard.h>
Public Types
enum coarse_mod_t {
CM_NEG_FDAC_OVER_4, CM_NEG_FDAC_OVER_8, CM_OFF, CM_POS_FDAC_OVER_8,
CM_POS_FDAC_OVER_4
}
Public Member Functions
~usrp_standard_tx ()
virtual bool set_interp_rate (unsigned int rate)
Set interpolator rate. rate must be in [4, 512] and a multiple of 4.
bool set_nchannels (int nchannels)
Set number of active channels. nchannels must be 1 or 2.
bool set_mux (int mux)
Set output mux configuration.
int determine_tx_mux_value (const usrp_subdev_spec &ss)
int determine_tx_mux_value (const usrp_subdev_spec &ss_a, const usrp_subdev_spec &ss_b)
virtual bool set_tx_freq (int channel, double freq)
set the frequency of the digital up converter.
unsigned int interp_rate () const
double tx_freq (int channel) const
int nchannels () const
int mux () const
bool tune (int chan, db_base_sptr db, double target_freq, usrp_tune_result *result)
High-level "tune" method. Works for the single channel case.
bool start ()
bool stop ()
Public Member Functions inherited from usrp_basic_tx
~usrp_basic_tx ()
bool set_fpga_tx_sample_rate_divisor (unsigned int div)
tell the fpga the rate tx samples are going to the D/A's
int write (const void *buf, int len, bool *underrun)
Write data to the A/D's via the FPGA.
void wait_for_completion ()
virtual long converter_rate () const
sampling rate of D/A converter
long dac_rate () const
int daughterboard_id (int which_side) const
Return daughterboard ID for given side [0,1].
bool set_pga (int which_amp, double gain_in_db)
Set Programmable Gain Amplifier (PGA)
double pga (int which_amp) const
Return programmable gain amplifier gain setting in dB.
double pga_min () const
Return minimum legal PGA gain in dB.
double pga_max () const
Return maximum legal PGA gain in dB.
double pga_db_per_step () const
Return hardware step size of PGA (linear in dB).
bool _write_oe (int which_side, int value, int mask)
Write direction register (output enables) for pins that go to daughterboard.
bool write_io (int which_side, int value, int mask)
Write daughterboard i/o pin value.
bool read_io (int which_side, int *value)
Read daughterboard i/o pin value.
int read_io (int which_side)
Read daughterboard i/o pin value.
bool write_refclk (int which_side, int value)
Write daughterboard refclk config register.
bool write_atr_mask (int which_side, int value)
bool write_atr_txval (int which_side, int value)
bool write_atr_rxval (int which_side, int value)
bool write_aux_dac (int which_side, int which_dac, int value)
Write auxiliary digital to analog converter.
bool read_aux_adc (int which_side, int which_adc, int *value)
Read auxiliary analog to digital converter.
int read_aux_adc (int which_side, int which_adc)
Read auxiliary analog to digital converter.
int block_size () const
returns current fusb block size
bool start ()
bool stop ()
Public Member Functions inherited from usrp_basic
virtual ~usrp_basic ()
std::vector< std::vector< db_base_sptr > > db () const
std::vector< db_base_sptr > db (int which_side)
bool is_valid (const usrp_subdev_spec &ss)
is the subdev_spec valid?
db_base_sptr selected_subdev (const usrp_subdev_spec &ss)
given a subdev_spec, return the corresponding daughterboard object.
long fpga_master_clock_freq () const
return frequency of master oscillator on USRP
void set_fpga_master_clock_freq (long master_clock)
int usb_data_rate () const
void set_verbose (bool on)
bool write_eeprom (int i2c_addr, int eeprom_offset, const std::string buf)
Write EEPROM on motherboard or any daughterboard.
std::string read_eeprom (int i2c_addr, int eeprom_offset, int len)
Read EEPROM on motherboard or any daughterboard.
bool write_i2c (int i2c_addr, const std::string buf)
Write to I2C peripheral.
std::string read_i2c (int i2c_addr, int len)
Read from I2C peripheral.
bool set_adc_offset (int which_adc, int offset)
Set ADC offset correction.
bool set_dac_offset (int which_dac, int offset, int offset_pin)
Set DAC offset correction.
bool set_adc_buffer_bypass (int which_adc, bool bypass)
Control ADC input buffer.
bool set_dc_offset_cl_enable (int bits, int mask)
Enable/disable automatic DC offset removal control loop in FPGA.
std::string serial_number ()
return the usrp's serial number.
bool write_atr_tx_delay (int value)
Clock ticks to delay rising of T/R signal.
bool write_atr_rx_delay (int value)
Clock ticks to delay falling edge of T/R signal.
bool common_set_pga (txrx_t txrx, int which_amp, double gain_in_db)
Set Programmable Gain Amplifier(PGA)
double common_pga (txrx_t txrx, int which_amp) const
Return programmable gain amplifier gain setting in dB.
double common_pga_min (txrx_t txrx) const
Return minimum legal PGA gain in dB.
double common_pga_max (txrx_t txrx) const
Return maximum legal PGA gain in dB.
double common_pga_db_per_step (txrx_t txrx) const
Return hardware step size of PGA(linear in dB).
bool _common_write_oe (txrx_t txrx, int which_side, int value, int mask)
Write direction register(output enables) for pins that go to daughterboard.
bool common_write_io (txrx_t txrx, int which_side, int value, int mask)
Write daughterboard i/o pin value.
bool common_read_io (txrx_t txrx, int which_side, int *value)
Read daughterboard i/o pin value.
int common_read_io (txrx_t txrx, int which_side)
Read daughterboard i/o pin value.
bool common_write_refclk (txrx_t txrx, int which_side, int value)
Write daughterboard refclk config register.
bool common_write_atr_mask (txrx_t txrx, int which_side, int value)
Automatic Transmit/Receive switching.
bool common_write_atr_txval (txrx_t txrx, int which_side, int value)
bool common_write_atr_rxval (txrx_t txrx, int which_side, int value)
bool common_write_aux_dac (txrx_t txrx, int which_side, int which_dac, int value)
Write auxiliary digital to analog converter.
bool common_read_aux_adc (txrx_t txrx, int which_side, int which_adc, int *value)
Read auxiliary analog to digital converter.
int common_read_aux_adc (txrx_t txrx, int which_side, int which_adc)
Read auxiliary analog to digital converter.
bool _set_led (int which_led, bool on)
bool _write_fpga_reg (int regno, int value)
Write FPGA register.
bool _read_fpga_reg (int regno, int *value)
Read FPGA register.
int _read_fpga_reg (int regno)
Read FPGA register.
bool _write_fpga_reg_masked (int regno, int value, int mask)
Write FPGA register with mask.
bool _write_9862 (int which_codec, int regno, unsigned char value)
Write AD9862 register.
bool _read_9862 (int which_codec, int regno, unsigned char *value) const
Read AD9862 register.
int _read_9862 (int which_codec, int regno) const
Read AD9862 register.
bool _write_spi (int optional_header, int enables, int format, std::string buf)
Write data to SPI bus peripheral.
std::string _read_spi (int optional_header, int enables, int format, int len)
bool start ()
Start data transfers. Called in base class to derived class order.
bool stop ()
Stop data transfers. Called in base class to derived class order.
Public Member Functions inherited from usrp_standard_common
bool has_rx_halfband () const
does the FPGA implement the final Rx half-band filter? If it doesn't, the maximum decimation factor with proper gain is 1/2 of what it would otherwise be.
int nddcs () const
number of digital downconverters implemented in the FPGA This will be 0, 1, 2 or 4.
bool has_tx_halfband () const
does the FPGA implement the initial Tx half-band filter?
int nducs () const
number of digital upconverters implemented in the FPGA This will be 0, 1, or 2.
Static Public Member Functions
static usrp_standard_tx_sptr make (int which_board, unsigned int interp_rate, int nchan=1, int mux=-1, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
invokes constructor, returns shared_ptr or shared_ptr equivalent of 0 if trouble
Static Public Member Functions inherited from usrp_basic_tx
static usrp_basic_tx * make (int which_board, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
invokes constructor, returns instance or 0 if trouble
Static Public Member Functions inherited from usrp_standard_common
static void calc_dxc_freq (double target_freq, double baseband_freq, double fs, double *dxc_freq, bool *inverted)
Calculate the frequency to use for setting the digital up or down converter.
Protected Member Functions
virtual bool set_coarse_modulator (int channel, coarse_mod_t cm)
usrp_standard_tx::coarse_mod_t coarse_modulator (int channel) const
usrp_standard_tx (int which_board, unsigned int interp_rate, int nchan=1, int mux=-1, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
bool write_hw_mux_reg ()
Protected Member Functions inherited from usrp_basic_tx
usrp_basic_tx (int which_board, int fusb_block_size=0, int fusb_nblocks=0, const std::string fpga_filename="", const std::string firmware_filename="")
bool set_tx_enable (bool on)
bool tx_enable () const
bool disable_tx ()
void restore_tx (bool on)
void probe_tx_slots (bool verbose)
Protected Member Functions inherited from usrp_basic
void shutdown_daughterboards ()
void init_db (usrp_basic_sptr u)
usrp_basic (int which_board, libusb_device_handle *open_interface(libusb_device *dev), const std::string fpga_filename="", const std::string firmware_filename="")
void set_usb_data_rate (int usb_data_rate)
advise usrp_basic of usb data rate (bytes/sec)
bool _write_aux_dac (int slot, int which_dac, int value)
Write auxiliary digital to analog converter.
bool _read_aux_adc (int slot, int which_adc, int *value)
Read auxiliary analog to digital converter.
int _read_aux_adc (int slot, int which_adc)
Read auxiliary analog to digital converter.
Protected Member Functions inherited from usrp_standard_common
usrp_standard_common (usrp_basic *parent)
Protected Attributes
unsigned int d_interp_rate
int d_nchan
int d_sw_mux
int d_hw_mux
double d_tx_freq [MAX_CHAN]
coarse_mod_t d_coarse_mod [MAX_CHAN]
unsigned char d_tx_modulator_shadow [MAX_CHAN]
Protected Attributes inherited from usrp_basic
libusb_device_handle * d_udh
struct libusb_context * d_ctx
int d_usb_data_rate
int d_bytes_per_poll
bool d_verbose
long d_fpga_master_clock_freq
unsigned int d_fpga_shadows [MAX_REGS]
int d_dbid [2]
std::vector< std::vector< db_base_sptr > > d_db
Static Protected Attributes
static const int MAX_CHAN = 2
Static Protected Attributes inherited from usrp_basic
static const int MAX_REGS = 128
Additional Inherited Members
Static Public Attributes inherited from usrp_basic
static const int READ_FAILED = -99999
magic value used on alternate register read interfaces
Detailed Description
The C++ interface the transmit side of the USRP
This is the recommended interface to USRP transmit functionality for applications that use the USRP but not GNU Radio.
Uses digital upconverter (coarse & fine modulators) in AD9862...
Member Enumeration Documentation
enum usrp_standard_tx::coarse_mod_t
Enumerator
CM_NEG_FDAC_OVER_4
CM_NEG_FDAC_OVER_8
CM_OFF
CM_POS_FDAC_OVER_8
CM_POS_FDAC_OVER_4
Constructor & Destructor Documentation
usrp_standard_tx::usrp_standard_tx (int which_board, unsigned int interp_rate, int nchan = 1, int mux = -1, int fusb_block_size = 0, int fusb_nblocks = 0, const std::string fpga_filename = "", const std::string firmware_filename = "") protected
References CM_OFF, d_coarse_mod, d_tx_modulator_shadow, usrp_basic::d_udh, MAX_CHAN, set_interp_rate(), set_mux(), set_nchannels(), set_tx_freq(), TX_MODULATOR_COARSE_MODULATION_NONE, TX_MODULATOR_DISABLE_NCO, and usrp_9862_write_many_all().
Referenced by make().
usrp_standard_tx::~usrp_standard_tx ()
Member Function Documentation
usrp_standard_tx::coarse_mod_t usrp_standard_tx::coarse_modulator (int channel) const protected
References CM_OFF, d_coarse_mod, and MAX_CHAN.
int usrp_standard_tx::determine_tx_mux_value (const usrp_subdev_spec & ss)
Determine the appropriate Tx mux value as a function of the subdevice choosen and the characteristics of the respective daughterboard.
References usrp_basic::db(), usrp_basic::is_valid(), usrp_subdev_spec::side, and usrp_subdev_spec::subdev.
Referenced by determine_tx_mux_value().
int usrp_standard_tx::determine_tx_mux_value (const usrp_subdev_spec & ss_a, const usrp_subdev_spec & ss_b)
References usrp_basic::_write_fpga_reg(), d_tx_freq, usrp_basic::d_verbose, usrp_basic_tx::dac_rate(), determine_tx_mux_value(), MAX_CHAN, set_tx_freq(), usrp_subdev_spec::side, and usrp_subdev_spec::subdev.
unsigned int usrp_standard_tx::interp_rate () const
References d_interp_rate.
usrp_standard_tx_sptr usrp_standard_tx::make (int which_board, unsigned int interp_rate, int nchan = 1, int mux = -1, int fusb_block_size = 0, int fusb_nblocks = 0, const std::string fpga_filename = "", const std::string firmware_filename = "") static
invokes constructor, returns shared_ptr or shared_ptr equivalent of 0 if trouble
Parameters
which_board Which USRP board on usb (not particularly useful; use 0)
interp_rate interpolation factor
nchan number of channels
mux Tx mux setting,
See also
set_mux
Parameters
fusb_block_size fast usb xfer block size. Must be a multiple of 512. Use zero for a reasonable default.
fusb_nblocks number of fast usb URBs to allocate. Use zero for a reasonable default.
fpga_filename Name of rbf file to load
firmware_filename Name of ihx file to load
References usrp_standard_tx().
Referenced by main().
int usrp_standard_tx::mux () const
References d_sw_mux.
Referenced by set_mux().
int usrp_standard_tx::nchannels () const
References d_nchan.
Referenced by set_interp_rate().
bool usrp_standard_tx::set_coarse_modulator (int channel, coarse_mod_t cm) protected virtual
References CM_NEG_FDAC_OVER_4, CM_NEG_FDAC_OVER_8, CM_OFF, CM_POS_FDAC_OVER_4, CM_POS_FDAC_OVER_8, d_coarse_mod, d_tx_modulator_shadow, MAX_CHAN, TX_MODULATOR_CM_MASK, TX_MODULATOR_COARSE_MODULATION_F_OVER_4, TX_MODULATOR_COARSE_MODULATION_F_OVER_8, and TX_MODULATOR_NEG_COARSE_TUNE.
Referenced by set_tx_freq().
bool usrp_standard_tx::set_interp_rate (unsigned int rate) virtual
Set interpolator rate. rate must be in [4, 512] and a multiple of 4.
The final complex sample rate across the USB is dac_freq () / interp_rate () * nchannels ()
References usrp_basic::_write_fpga_reg(), d_interp_rate, usrp_basic_tx::dac_rate(), usrp_basic_tx::disable_tx(), nchannels(), usrp_basic_tx::restore_tx(), and usrp_basic::set_usb_data_rate().
Referenced by usrp_standard_tx().
bool usrp_standard_tx::set_mux (int mux)
Set output mux configuration.
    3                   2                   1
  1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
 +----------------------------—+----—+----—+----—+----—+
 |                               | DAC3  | DAC2  | DAC1  |  DAC0 |
 +----------------------------—+----—+----—+----—+----—+
 There are two interpolators with complex inputs and outputs.
 There are four DACs.
 Each 4-bit DACx field specifies the source for the DAC and
 whether or not that DAC is enabled.  Each subfield is coded
 like this:
    3 2 1 0
   +-+--—+
   |E|  N  |
   +-+--—+
 Where E is set if the DAC is enabled, and N specifies which
 interpolator output is connected to this DAC.
  N   which interp output
  0   chan 0 I
  1   chan 0 Q
  2   chan 1 I
  3   chan 1 Q
References d_hw_mux, d_sw_mux, mux(), and write_hw_mux_reg().
Referenced by usrp_standard_tx().
bool usrp_standard_tx::set_nchannels (int nchannels)
Set number of active channels. nchannels must be 1 or 2.
The final complex sample rate across the USB is dac_freq () / decim_rate () * nchannels ()
References d_nchan, usrp_standard_common::nducs(), and write_hw_mux_reg().
Referenced by usrp_standard_tx().
bool usrp_standard_tx::set_tx_freq (int channel, double freq) virtual
set the frequency of the digital up converter.
channel must be in the range [0,1]. freq is the center frequency in Hz. It must be in the range [-44M, 44M]. The frequency specified is quantized. Use tx_freq to retrieve the actual value used.
References usrp_basic::_write_9862(), CM_NEG_FDAC_OVER_4, CM_NEG_FDAC_OVER_8, CM_OFF, CM_POS_FDAC_OVER_4, CM_POS_FDAC_OVER_8, d_tx_freq, d_tx_modulator_shadow, usrp_basic::d_verbose, usrp_basic_tx::dac_rate(), MAX_CHAN, REG_TX_MODULATOR, REG_TX_NCO_FTW_15_8, REG_TX_NCO_FTW_23_16, REG_TX_NCO_FTW_7_0, set_coarse_modulator(), TX_MODULATOR_ENABLE_NCO, and TX_MODULATOR_NEG_FINE_TUNE.
Referenced by determine_tx_mux_value(), duc_control::set_dxc_freq(), and usrp_standard_tx().
bool usrp_standard_tx::start ()
References usrp_basic_tx::start().
bool usrp_standard_tx::stop ()
References usrp_basic_tx::stop().
bool usrp_standard_tx::tune (int chan, db_base_sptr db, double target_freq, usrp_tune_result * result)
High-level "tune" method. Works for the single channel case.
This method adjusts both the daughterboard LO and the DUC so that DC in the complex baseband samples ends up at RF target_freq.
Parameters
chan which DUC channel we're controlling (usually == which_side).
db the daughterboard we're controlling.
target_freq the RF frequency we want our baseband translated to.
[out] result details how the hardware was configured.
Returns
true iff everything was successful.
References usrp_basic_tx::converter_rate().
double usrp_standard_tx::tx_freq (int channel) const
References d_tx_freq, and MAX_CHAN.
Referenced by duc_control::dxc_freq().
bool usrp_standard_tx::write_hw_mux_reg () protected
References usrp_basic::_write_fpga_reg(), d_hw_mux, d_nchan, usrp_basic_tx::disable_tx(), and usrp_basic_tx::restore_tx().
Referenced by set_mux(), and set_nchannels().
Member Data Documentation
coarse_mod_t usrp_standard_tx::d_coarse_mod[MAX_CHAN] protected
Referenced by coarse_modulator(), set_coarse_modulator(), and usrp_standard_tx().
int usrp_standard_tx::d_hw_mux protected
Referenced by set_mux(), and write_hw_mux_reg().
unsigned int usrp_standard_tx::d_interp_rate protected
Referenced by interp_rate(), and set_interp_rate().
int usrp_standard_tx::d_nchan protected
Referenced by nchannels(), set_nchannels(), and write_hw_mux_reg().
int usrp_standard_tx::d_sw_mux protected
Referenced by mux(), and set_mux().
double usrp_standard_tx::d_tx_freq[MAX_CHAN] protected
Referenced by determine_tx_mux_value(), set_tx_freq(), and tx_freq().
unsigned char usrp_standard_tx::d_tx_modulator_shadow[MAX_CHAN] protected
Referenced by set_coarse_modulator(), set_tx_freq(), and usrp_standard_tx().
const int usrp_standard_tx::MAX_CHAN = 2 static protected
Referenced by coarse_modulator(), determine_tx_mux_value(), set_coarse_modulator(), set_tx_freq(), tx_freq(), and usrp_standard_tx().
The documentation for this class was generated from the following files:
usrp_standard.h
usrp_standard.cc