Universal Software Radio Peripheral: _AD4360_common Class Reference
_AD4360_common Class Reference abstract
#include <db_flexrf.h>
Public Member Functions
_AD4360_common ()
virtual ~_AD4360_common ()
virtual double freq_min ()=0
virtual double freq_max ()=0
bool _compute_regs (double refclk_freq, double freq, int &retR, int &retcontrol, int &retN, double &retfreq)
int _compute_control_reg ()
virtual int _refclk_divisor ()
int _prescaler ()
void R_DIV (int div)
Protected Attributes
int d_R_RSV
int d_BSC
int d_TEST
int d_LDP
int d_ABP
int d_N_RSV
int d_PL
int d_MTLD
int d_CPG
int d_CP3S
int d_PDP
int d_MUXOUT
int d_CR
int d_PC
int d_A_DIV
int d_B_DIV
int d_R_DIV
int d_P
int d_PD
int d_CP2
int d_CP1
int d_DIVSEL
int d_DIV2
int d_CPGAIN
int d_freq_mult
Constructor & Destructor Documentation
_AD4360_common::_AD4360_common ()
References flexrf_base::d_PD.
_AD4360_common::~_AD4360_common () virtual
Member Function Documentation
int _AD4360_common::_compute_control_reg ()
References flexrf_base::d_PD.
Referenced by flexrf_base::_compute_control_reg().
bool _AD4360_common::_compute_regs (double refclk_freq, double freq, int & retR, int & retcontrol, int & retN, double & retfreq)
References flexrf_base::_compute_control_reg().
Referenced by db_flexrf_2200_tx::_compute_regs(), db_flexrf_2200_rx::_compute_regs(), db_flexrf_2400_tx::_compute_regs(), db_flexrf_2400_rx::_compute_regs(), db_flexrf_1200_tx::_compute_regs(), db_flexrf_1200_rx::_compute_regs(), db_flexrf_1800_tx::_compute_regs(), db_flexrf_1800_rx::_compute_regs(), db_flexrf_900_tx::_compute_regs(), db_flexrf_900_rx::_compute_regs(), db_flexrf_400_tx::_compute_regs(), and db_flexrf_400_rx::_compute_regs().
int _AD4360_common::_prescaler ()
int _AD4360_common::_refclk_divisor () virtual
Referenced by flexrf_base::_refclk_divisor().
virtual double _AD4360_common::freq_max () pure virtual
Implemented in _400_common, _900_common, _1800_common, _1200_common, _2400_common, and _2200_common.
Referenced by flexrf_base::freq_max().
virtual double _AD4360_common::freq_min () pure virtual
Implemented in _400_common, _900_common, _1800_common, _1200_common, _2400_common, and _2200_common.
Referenced by flexrf_base::freq_min().
void _AD4360_common::R_DIV (int div) inline
Referenced by db_flexrf_1200_rx_mimo_a::db_flexrf_1200_rx_mimo_a(), db_flexrf_1200_rx_mimo_b::db_flexrf_1200_rx_mimo_b(), db_flexrf_1200_tx_mimo_a::db_flexrf_1200_tx_mimo_a(), db_flexrf_1200_tx_mimo_b::db_flexrf_1200_tx_mimo_b(), db_flexrf_1800_rx_mimo_a::db_flexrf_1800_rx_mimo_a(), db_flexrf_1800_rx_mimo_b::db_flexrf_1800_rx_mimo_b(), db_flexrf_1800_tx_mimo_a::db_flexrf_1800_tx_mimo_a(), db_flexrf_1800_tx_mimo_b::db_flexrf_1800_tx_mimo_b(), db_flexrf_2400_rx_mimo_a::db_flexrf_2400_rx_mimo_a(), db_flexrf_2400_rx_mimo_b::db_flexrf_2400_rx_mimo_b(), db_flexrf_2400_tx_mimo_a::db_flexrf_2400_tx_mimo_a(), db_flexrf_2400_tx_mimo_b::db_flexrf_2400_tx_mimo_b(), db_flexrf_400_rx_mimo_a::db_flexrf_400_rx_mimo_a(), db_flexrf_400_rx_mimo_b::db_flexrf_400_rx_mimo_b(), db_flexrf_400_tx_mimo_a::db_flexrf_400_tx_mimo_a(), db_flexrf_400_tx_mimo_b::db_flexrf_400_tx_mimo_b(), db_flexrf_900_rx_mimo_a::db_flexrf_900_rx_mimo_a(), db_flexrf_900_rx_mimo_b::db_flexrf_900_rx_mimo_b(), db_flexrf_900_tx_mimo_a::db_flexrf_900_tx_mimo_a(), and db_flexrf_900_tx_mimo_b::db_flexrf_900_tx_mimo_b().
Member Data Documentation
int _AD4360_common::d_A_DIV protected
int _AD4360_common::d_ABP protected
int _AD4360_common::d_B_DIV protected
int _AD4360_common::d_BSC protected
int _AD4360_common::d_CP1 protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_CP2 protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_CP3S protected
int _AD4360_common::d_CPG protected
int _AD4360_common::d_CPGAIN protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_CR protected
int _AD4360_common::d_DIV2 protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_rx::_400_rx(), _400_tx::_400_tx(), and _900_common::_900_common().
int _AD4360_common::d_DIVSEL protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_freq_mult protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_LDP protected
int _AD4360_common::d_MTLD protected
int _AD4360_common::d_MUXOUT protected
int _AD4360_common::d_N_RSV protected
int _AD4360_common::d_P protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_PC protected
int _AD4360_common::d_PD protected
int _AD4360_common::d_PDP protected
int _AD4360_common::d_PL protected
int _AD4360_common::d_R_DIV protected
Referenced by _1200_common::_1200_common(), _1800_common::_1800_common(), _2200_common::_2200_common(), _2400_common::_2400_common(), _400_common::_400_common(), and _900_common::_900_common().
int _AD4360_common::d_R_RSV protected
int _AD4360_common::d_TEST protected
The documentation for this class was generated from the following files:
db_flexrf.h
db_flexrf.cc