Universal Software Radio Peripheral: fusb_devhandle Class Reference
fusb_devhandle Class Reference abstract
abstract usb device handle
#include <fusb.h>
Public Member Functions
fusb_devhandle (libusb_device_handle *udh)
virtual ~fusb_devhandle ()
virtual fusb_ephandle * make_ephandle (int endpoint, bool input_p, int block_size=0, int nblocks=0)=0
return an ephandle of the correct subtype
libusb_device_handle * get_usb_dev_handle () const
Protected Attributes
libusb_device_handle * d_udh
Detailed Description
abstract usb device handle
Constructor & Destructor Documentation
fusb_devhandle::fusb_devhandle (libusb_device_handle * udh)
fusb_devhandle::~fusb_devhandle () virtual
Member Function Documentation
libusb_device_handle* fusb_devhandle::get_usb_dev_handle () const inline
References d_udh.
Referenced by fusb_ephandle_win32::fusb_ephandle_win32(), fusb_ephandle_generic::read(), fusb_ephandle_ra_wb::read(), fusb_ephandle_ra_wb::start(), fusb_ephandle_darwin::start(), fusb_ephandle_ra_wb::stop(), fusb_ephandle_ra_wb::wait_for_completion(), fusb_ephandle_generic::write(), and fusb_ephandle_ra_wb::write().
virtual fusb_ephandle* fusb_devhandle::make_ephandle (int endpoint, bool input_p, int block_size = 0, int nblocks = 0) pure virtual
return an ephandle of the correct subtype
Implemented in fusb_devhandle_darwin, fusb_devhandle_libusb1, fusb_devhandle_linux, fusb_devhandle_generic, fusb_devhandle_ra_wb, and fusb_devhandle_win32.
Referenced by usrp_basic_rx::usrp_basic_rx(), and usrp_basic_tx::usrp_basic_tx().
Member Data Documentation
libusb_device_handle* fusb_devhandle::d_udh protected
Referenced by fusb_devhandle_linux::_cancel_urb(), fusb_devhandle_linux::_reap(), fusb_devhandle_linux::_submit_urb(), and get_usb_dev_handle().
The documentation for this class was generated from the following files:
fusb.h
fusb.cc