Universal Software Radio Peripheral: db_flexrf_900_rx Class Reference
db_flexrf_900_rx Class Reference
#include <db_flexrf.h>
Public Member Functions
db_flexrf_900_rx (usrp_basic_sptr usrp, int which)
~db_flexrf_900_rx ()
float gain_min ()
float gain_max ()
float gain_db_per_step ()
bool i_and_q_swapped ()
bool _compute_regs (double freq, int &retR, int &retcontrol, int &retN, double &retfreq)
Public Member Functions inherited from flexrf_base_rx
flexrf_base_rx (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base_rx ()
bool set_auto_tr (bool on)
bool select_rx_antenna (int which_antenna)
bool select_rx_antenna (const std::string &which_antenna)
bool set_gain (float gain)
Public Member Functions inherited from flexrf_base
flexrf_base (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base ()
struct freq_result_t set_freq (double freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_bw (float bw)
Additional Inherited Members
Protected Member Functions inherited from flexrf_base_rx
void shutdown ()
Protected Member Functions inherited from flexrf_base
void _write_all (int R, int control, int N)
void _write_control (int control)
void _write_R (int R)
void _write_N (int N)
void _write_it (int v)
bool _lock_detect ()
int _compute_control_reg ()
int _refclk_divisor ()
bool _set_pga (float pga_gain)
int power_on ()
int power_off ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
Protected Attributes inherited from flexrf_base
bool d_first
int d_spi_format
int d_spi_enable
int d_power_on
int d_PD
_AD4360_common * d_common
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
db_flexrf_900_rx::db_flexrf_900_rx (usrp_basic_sptr usrp, int which)
References flexrf_base::d_common, gain_max(), gain_min(), and flexrf_base_rx::set_gain().
db_flexrf_900_rx::~db_flexrf_900_rx ()
Member Function Documentation
bool db_flexrf_900_rx::_compute_regs (double freq, int & retR, int & retcontrol, int & retN, double & retfreq) virtual
Reimplemented from flexrf_base.
References _AD4360_common::_compute_regs(), db_base::_refclk_freq(), and flexrf_base::d_common.
float db_flexrf_900_rx::gain_db_per_step () virtual
Implements db_base.
float db_flexrf_900_rx::gain_max () virtual
Implements db_base.
References usrp_basic::pga_max(), and db_base::usrp().
Referenced by db_flexrf_900_rx().
float db_flexrf_900_rx::gain_min () virtual
Implements db_base.
References usrp_basic::pga_min(), and db_base::usrp().
Referenced by db_flexrf_900_rx().
bool db_flexrf_900_rx::i_and_q_swapped () virtual
Reimplemented from db_base.
The documentation for this class was generated from the following files:
db_flexrf.h
db_flexrf.cc