Universal Software Radio Peripheral: flexrf_base Class Reference
flexrf_base Class Reference
#include <db_flexrf.h>
Public Member Functions
flexrf_base (usrp_basic_sptr usrp, int which, int _power_on=0)
~flexrf_base ()
struct freq_result_t set_freq (double freq)
bool is_quadrature ()
double freq_min ()
double freq_max ()
Public Member Functions inherited from db_base
db_base (boost::shared_ptr< usrp_basic > usrp, int which)
virtual ~db_base ()
int dbid ()
std::string name ()
std::string side_and_name ()
int which ()
bool bypass_adc_buffers (bool bypass)
bool set_atr_mask (int v)
bool set_atr_txval (int v)
bool set_atr_rxval (int v)
bool set_atr_tx_delay (int v)
bool set_atr_rx_delay (int v)
bool set_lo_offset (double offset)
double lo_offset ()
virtual float gain_min ()=0
virtual float gain_max ()=0
virtual float gain_db_per_step ()=0
virtual bool set_gain (float gain)=0
virtual bool i_and_q_swapped ()
virtual bool spectrum_inverted ()
virtual bool set_enable (bool on)
virtual bool set_auto_tr (bool on)
virtual bool select_rx_antenna (int which_antenna)
virtual bool select_rx_antenna (const std::string &which_antenna)
virtual bool set_bw (float bw)
Protected Member Functions
void _write_all (int R, int control, int N)
void _write_control (int control)
void _write_R (int R)
void _write_N (int N)
void _write_it (int v)
bool _lock_detect ()
virtual bool _compute_regs (double freq, int &retR, int &retcontrol, int &retN, double &retfreq)
int _compute_control_reg ()
int _refclk_divisor ()
bool _set_pga (float pga_gain)
int power_on ()
int power_off ()
Protected Member Functions inherited from db_base
void _enable_refclk (bool enable)
virtual double _refclk_freq ()
usrp_basic * usrp ()
virtual void shutdown ()
Protected Attributes
bool d_first
int d_spi_format
int d_spi_enable
int d_power_on
int d_PD
_AD4360_common * d_common
Protected Attributes inherited from db_base
bool d_is_shutdown
usrp_basic * d_raw_usrp
int d_which
double d_lo_offset
Constructor & Destructor Documentation
flexrf_base::flexrf_base (usrp_basic_sptr usrp, int which, int _power_on = 0)
References db_base::_enable_refclk(), usrp_basic::_write_oe(), d_first, d_spi_format, db_base::d_which, db_base::set_auto_tr(), and db_base::usrp().
flexrf_base::~flexrf_base ()
References d_common.
Member Function Documentation
int flexrf_base::_compute_control_reg () protected
References _AD4360_common::_compute_control_reg(), and d_common.
Referenced by _AD4360_common::_compute_regs(), flexrf_base_tx::shutdown(), and flexrf_base_rx::shutdown().
bool flexrf_base::_compute_regs (double freq, int & retR, int & retcontrol, int & retN, double & retfreq) protected virtual
Reimplemented in db_flexrf_400_rx, db_flexrf_400_tx, db_flexrf_900_rx, db_flexrf_900_tx, db_flexrf_1800_rx, db_flexrf_1800_tx, db_flexrf_1200_rx, db_flexrf_1200_tx, db_flexrf_2400_rx, db_flexrf_2400_tx, db_flexrf_2200_rx, and db_flexrf_2200_tx.
Referenced by set_freq().
bool flexrf_base::_lock_detect () protected
References db_base::d_which, PLL_LOCK_DETECT, and db_base::usrp().
Referenced by set_freq().
int flexrf_base::_refclk_divisor () protected virtual
Reimplemented from db_base.
Reimplemented in db_flexrf_400_rx_mimo_b, db_flexrf_400_tx_mimo_b, db_flexrf_400_rx_mimo_a, db_flexrf_400_tx_mimo_a, db_flexrf_900_rx_mimo_b, db_flexrf_900_tx_mimo_b, db_flexrf_900_rx_mimo_a, db_flexrf_900_tx_mimo_a, db_flexrf_1200_rx_mimo_b, db_flexrf_1200_tx_mimo_b, db_flexrf_1200_rx_mimo_a, db_flexrf_1200_tx_mimo_a, db_flexrf_1800_rx_mimo_b, db_flexrf_1800_tx_mimo_b, db_flexrf_1800_rx_mimo_a, db_flexrf_1800_tx_mimo_a, db_flexrf_2400_rx_mimo_b, db_flexrf_2400_tx_mimo_b, db_flexrf_2400_rx_mimo_a, and db_flexrf_2400_tx_mimo_a.
References _AD4360_common::_refclk_divisor(), and d_common.
bool flexrf_base::_set_pga (float pga_gain) protected
References db_base::d_which, usrp_basic::set_pga(), and db_base::usrp().
Referenced by flexrf_base_tx::set_gain(), and flexrf_base_rx::set_gain().
void flexrf_base::_write_all (int R, int control, int N) protected
References _write_control(), _write_N(), _write_R(), and d_first.
Referenced by set_freq().
void flexrf_base::_write_control (int control) protected
References _write_it().
Referenced by _write_all(), flexrf_base_tx::shutdown(), and flexrf_base_rx::shutdown().
void flexrf_base::_write_it (int v) protected
References usrp_basic::_write_spi(), d_spi_enable, d_spi_format, and db_base::usrp().
Referenced by _write_control(), _write_N(), and _write_R().
void flexrf_base::_write_N (int N) protected
References _write_it().
Referenced by _write_all().
void flexrf_base::_write_R (int R) protected
References _write_it().
Referenced by _write_all().
double flexrf_base::freq_max () virtual
Implements db_base.
References d_common, and _AD4360_common::freq_max().
Referenced by _1200_common::~_1200_common(), _1800_common::~_1800_common(), _2200_common::~_2200_common(), _2400_common::~_2400_common(), _400_common::~_400_common(), and _900_common::~_900_common().
double flexrf_base::freq_min () virtual
Implements db_base.
References d_common, and _AD4360_common::freq_min().
Referenced by _1200_common::~_1200_common(), _1800_common::~_1800_common(), _2200_common::~_2200_common(), _2400_common::~_2400_common(), _400_common::~_400_common(), and _900_common::~_900_common().
bool flexrf_base::is_quadrature () virtual
Implements db_base.
int flexrf_base::power_off () inline protected
Referenced by flexrf_base_tx::shutdown(), and flexrf_base_rx::shutdown().
int flexrf_base::power_on () inline protected
References d_power_on.
Referenced by flexrf_base_rx::flexrf_base_rx(), and flexrf_base_tx::flexrf_base_tx().
struct freq_result_t flexrf_base::set_freq (double freq) virtual
Implements db_base.
References _compute_regs(), _lock_detect(), _write_all(), freq_result_t::baseband_freq, db_base::d_lo_offset, and freq_result_t::ok.
Member Data Documentation
_AD4360_common* flexrf_base::d_common protected
Referenced by _compute_control_reg(), db_flexrf_2200_tx::_compute_regs(), db_flexrf_2200_rx::_compute_regs(), db_flexrf_2400_tx::_compute_regs(), db_flexrf_2400_rx::_compute_regs(), db_flexrf_1200_tx::_compute_regs(), db_flexrf_1200_rx::_compute_regs(), db_flexrf_1800_tx::_compute_regs(), db_flexrf_1800_rx::_compute_regs(), db_flexrf_900_tx::_compute_regs(), db_flexrf_900_rx::_compute_regs(), db_flexrf_400_tx::_compute_regs(), db_flexrf_400_rx::_compute_regs(), _refclk_divisor(), db_flexrf_1200_rx::db_flexrf_1200_rx(), db_flexrf_1200_rx_mimo_a::db_flexrf_1200_rx_mimo_a(), db_flexrf_1200_rx_mimo_b::db_flexrf_1200_rx_mimo_b(), db_flexrf_1200_tx::db_flexrf_1200_tx(), db_flexrf_1200_tx_mimo_a::db_flexrf_1200_tx_mimo_a(), db_flexrf_1200_tx_mimo_b::db_flexrf_1200_tx_mimo_b(), db_flexrf_1800_rx::db_flexrf_1800_rx(), db_flexrf_1800_rx_mimo_a::db_flexrf_1800_rx_mimo_a(), db_flexrf_1800_rx_mimo_b::db_flexrf_1800_rx_mimo_b(), db_flexrf_1800_tx::db_flexrf_1800_tx(), db_flexrf_1800_tx_mimo_a::db_flexrf_1800_tx_mimo_a(), db_flexrf_1800_tx_mimo_b::db_flexrf_1800_tx_mimo_b(), db_flexrf_2200_rx::db_flexrf_2200_rx(), db_flexrf_2200_tx::db_flexrf_2200_tx(), db_flexrf_2400_rx::db_flexrf_2400_rx(), db_flexrf_2400_rx_mimo_a::db_flexrf_2400_rx_mimo_a(), db_flexrf_2400_rx_mimo_b::db_flexrf_2400_rx_mimo_b(), db_flexrf_2400_tx::db_flexrf_2400_tx(), db_flexrf_2400_tx_mimo_a::db_flexrf_2400_tx_mimo_a(), db_flexrf_2400_tx_mimo_b::db_flexrf_2400_tx_mimo_b(), db_flexrf_400_rx::db_flexrf_400_rx(), db_flexrf_400_rx_mimo_a::db_flexrf_400_rx_mimo_a(), db_flexrf_400_rx_mimo_b::db_flexrf_400_rx_mimo_b(), db_flexrf_400_tx::db_flexrf_400_tx(), db_flexrf_400_tx_mimo_a::db_flexrf_400_tx_mimo_a(), db_flexrf_400_tx_mimo_b::db_flexrf_400_tx_mimo_b(), db_flexrf_900_rx::db_flexrf_900_rx(), db_flexrf_900_rx_mimo_a::db_flexrf_900_rx_mimo_a(), db_flexrf_900_rx_mimo_b::db_flexrf_900_rx_mimo_b(), db_flexrf_900_tx::db_flexrf_900_tx(), db_flexrf_900_tx_mimo_a::db_flexrf_900_tx_mimo_a(), db_flexrf_900_tx_mimo_b::db_flexrf_900_tx_mimo_b(), freq_max(), freq_min(), and ~flexrf_base().
bool flexrf_base::d_first protected
Referenced by _write_all(), and flexrf_base().
int flexrf_base::d_PD protected
Referenced by _AD4360_common::_AD4360_common(), _AD4360_common::_compute_control_reg(), flexrf_base_tx::shutdown(), and flexrf_base_rx::shutdown().
int flexrf_base::d_power_on protected
Referenced by power_on().
int flexrf_base::d_spi_enable protected
Referenced by _write_it(), flexrf_base_rx::flexrf_base_rx(), and flexrf_base_tx::flexrf_base_tx().
int flexrf_base::d_spi_format protected
Referenced by _write_it(), and flexrf_base().
The documentation for this class was generated from the following files:
db_flexrf.h
db_flexrf.cc