Universal Software Radio Peripheral: db_util.h File Reference
db_util.h File Reference
#include <string>
#include <vector>
Functions
std::string int_seq_to_str (std::vector< int > &seq)
std::vector< int > str_to_int_seq (std::string str)
Function Documentation
std::string int_seq_to_str (std::vector< int > & seq)
Referenced by db_bitshark_rx::set_bw(), db_bitshark_rx::set_clock_scheme(), db_dtt768::set_freq(), db_dtt754::set_freq(), db_bitshark_rx::set_freq(), db_tv_rx::set_freq(), db_bitshark_rx::set_gain(), and db_dbs_rx::shutdown().
std::vector<int> str_to_int_seq (std::string str)
Referenced by db_dbs_rx::shutdown().