Universal Software Radio Peripheral: db_dtt754.cc File Reference
db_dtt754.cc File Reference
#include <usrp/db_dtt754.h>
#include <db_base_impl.h>
Functions
int control_byte_1 ()
int control_byte_2 ()
int bandswitch_byte (float freq, float bw)
Function Documentation
int bandswitch_byte (float freq, float bw)
Referenced by db_dtt754::set_freq().
int control_byte_1 ()
Referenced by db_dtt754::set_freq().
int control_byte_2 ()
Referenced by db_dtt754::set_freq().