Universal Software Radio Peripheral: test_usrp_standard_tx.cc File Reference
test_usrp_standard_tx.cc File Reference
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <assert.h>
#include <math.h>
#include "time_stuff.h"
#include <usrp/usrp_standard.h>
#include <usrp/usrp_bytesex.h>
#include <boost/program_options.hpp>
Enumerations
enum { GR_SIN_WAVE, GR_CONST_WAVE }
Functions
usrp_subdev_spec str_to_subdev (std::string spec_str)
int main (int argc, char **argv)
Variables
char * prog_name
Enumeration Type Documentation
anonymous enum
Enumerator
GR_SIN_WAVE
GR_CONST_WAVE
Function Documentation
int main (int argc, char ** argv)
References usrp_tune_result::baseband_freq, usrp_tune_result::dxc_freq, GR_CONST_WAVE, GR_SIN_WAVE, usrp_tune_result::inverted, usrp_standard_tx::make(), optarg, usrp_tune_result::residual_freq, and str_to_subdev().
usrp_subdev_spec str_to_subdev (std::string spec_str)
References get_cpu_usage(), get_elapsed_time(), GR_CONST_WAVE, prog_name, usrp_subdev_spec::side, and usrp_subdev_spec::subdev.
Referenced by main().
Variable Documentation
char* prog_name
Referenced by str_to_subdev().