Universal Software Radio Peripheral: time_stuff.h File Reference
time_stuff.h File Reference
Functions
double get_cpu_usage (void)
double get_elapsed_time (void)
Function Documentation
double get_cpu_usage (void)
Referenced by main(), and str_to_subdev().
double get_elapsed_time (void)
Referenced by main(), and str_to_subdev().