Universal Software Radio Peripheral: usrper.cc File Reference
usrper.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <assert.h>
#include <errno.h>
#include "usrp/usrp_prims.h"
#include "usrp_spi_defs.h"
Macros
#define CHKARGS(n) if (nopts != n) usage (); else
Functions
int main (int argc, char **argv)
Variables
char * prog_name
Macro Definition Documentation
#define CHKARGS (n) if (nopts != n) usage (); else
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
References CHKARGS, getopt(), optarg, optind, prog_name, usrp_9862_read(), usrp_9862_write(), usrp_close_interface(), usrp_find_device(), usrp_fx2_p(), usrp_get_hash(), usrp_i2c_read(), usrp_i2c_write(), usrp_load_firmware(), usrp_load_fpga(), usrp_load_standard_bits(), usrp_one_time_init(), usrp_open_cmd_interface(), usrp_set_fpga_reset(), usrp_set_fpga_rx_enable(), usrp_set_fpga_tx_enable(), usrp_set_hash(), usrp_set_led(), usrp_unconfigured_usrp_p(), and usrp_write_fpga_reg().
Variable Documentation
char* prog_name
Referenced by main().