Universal Software Radio Peripheral: usrp_cal_dc_offset.cc File Reference
usrp_cal_dc_offset.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <assert.h>
#include <math.h>
#include <boost/scoped_ptr.hpp>
#include <usrp/usrp_local_sighandler.h>
#include <usrp/usrp_standard.h>
#include <usrp/usrp_bytesex.h>
Functions
int main (int argc, char **argv)
Variables
char * prog_name
Function Documentation
int main (int argc, char ** argv)
References usrp_standard_rx::FPGA_MODE_NORMAL, getopt(), usrp_standard_rx::make(), usrp_signal::name(), optarg, and usrp_local_sighandler::throw_signal().
Variable Documentation
char* prog_name