Universal Software Radio Peripheral: usrp_dbid.cc File Reference
usrp_dbid.cc File Reference
#include <usrp/usrp_prims.h>
#include <usrp/usrp_dbid.h>
#include <stdio.h>
Macros
#define NELEM(x) sizeof(x)/sizeof(x[0])
Functions
const std::string usrp_dbid_to_string (int dbid)
usrp daughterboard id to name mapping
Macro Definition Documentation
#define NELEM (x) sizeof(x)/sizeof(x[0])
Referenced by usrp_dbid_to_string().
Function Documentation
const std::string usrp_dbid_to_string (int dbid)
usrp daughterboard id to name mapping
References NELEM.
Referenced by db_base::name(), usrp_basic_rx::probe_rx_slots(), and usrp_basic_tx::probe_tx_slots().
Variable Documentation
unsigned short dbid
Referenced by db_base::usrp().
const char* name
Referenced by db_base::usrp().