Universal Software Radio Peripheral: usrp_primsi.h File Reference
usrp_primsi.h File Reference
#include "usrp/usrp_prims.h"
Functions
libusb_device_handle * usrp_open_interface (libusb_device *dev, int interface, int altinterface)
int write_cmd (libusb_device_handle *udh, int request, int value, int index, unsigned char *bytes, int len)
libusb_device * _get_usb_device (libusb_device_handle *udh)
libusb_device_descriptor _get_usb_device_descriptor (libusb_device *q)
int _get_usb_string_descriptor (libusb_device_handle *udh, int index, unsigned char *data, int length)
int _usb_control_transfer (libusb_device_handle *udh, int request_type, int request, int value, int index, unsigned char *data, int length, unsigned int timeout)
Function Documentation
libusb_device* _get_usb_device (libusb_device_handle * udh)
Referenced by usrp_9862_write_many_all(), usrp_read_fpga_reg(), usrp_serial_number(), and usrp_write_fpga_reg().
libusb_device_descriptor _get_usb_device_descriptor (libusb_device * q)
int _get_usb_string_descriptor (libusb_device_handle * udh, int index, unsigned char * data, int length)
Referenced by usrp_serial_number().
int _usb_control_transfer (libusb_device_handle * udh, int request_type, int request, int value, int index, unsigned char * data, int length, unsigned int timeout)
Referenced by usrp_get_hash(), usrp_open_tx_interface(), and usrp_set_hash().
libusb_device_handle* usrp_open_interface (libusb_device * dev, int interface, int altinterface)
int write_cmd (libusb_device_handle * udh, int request, int value, int index, unsigned char * bytes, int len)
Referenced by _usrp_get_status(), usrp_get_hash(), usrp_i2c_read(), usrp_i2c_write(), usrp_open_tx_interface(), usrp_set_led(), usrp_spi_read(), and usrp_spi_write().