# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pmt_swig', [dirname(__file__)])
        except ImportError:
            import _pmt_swig
            return _pmt_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_pmt_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pmt_swig = swig_import_helper()
    del swig_import_helper
else:
    import _pmt_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class swig_int_ptr(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        this = _pmt_swig.new_swig_int_ptr()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _pmt_swig.delete_swig_int_ptr
    __del__ = lambda self: None
swig_int_ptr_swigregister = _pmt_swig.swig_int_ptr_swigregister
swig_int_ptr_swigregister(swig_int_ptr)


def pmt_is_bool(obj):
    return _pmt_swig.pmt_is_bool(obj)
pmt_is_bool = _pmt_swig.pmt_is_bool

def pmt_is_true(obj):
    return _pmt_swig.pmt_is_true(obj)
pmt_is_true = _pmt_swig.pmt_is_true

def pmt_is_false(obj):
    return _pmt_swig.pmt_is_false(obj)
pmt_is_false = _pmt_swig.pmt_is_false

def pmt_from_bool(val):
    return _pmt_swig.pmt_from_bool(val)
pmt_from_bool = _pmt_swig.pmt_from_bool

def pmt_to_bool(val):
    return _pmt_swig.pmt_to_bool(val)
pmt_to_bool = _pmt_swig.pmt_to_bool

def pmt_is_symbol(obj):
    return _pmt_swig.pmt_is_symbol(obj)
pmt_is_symbol = _pmt_swig.pmt_is_symbol

def pmt_string_to_symbol(s):
    return _pmt_swig.pmt_string_to_symbol(s)
pmt_string_to_symbol = _pmt_swig.pmt_string_to_symbol

def pmt_intern(s):
    return _pmt_swig.pmt_intern(s)
pmt_intern = _pmt_swig.pmt_intern

def pmt_symbol_to_string(sym):
    return _pmt_swig.pmt_symbol_to_string(sym)
pmt_symbol_to_string = _pmt_swig.pmt_symbol_to_string

def pmt_is_number(obj):
    return _pmt_swig.pmt_is_number(obj)
pmt_is_number = _pmt_swig.pmt_is_number

def pmt_is_integer(x):
    return _pmt_swig.pmt_is_integer(x)
pmt_is_integer = _pmt_swig.pmt_is_integer

def pmt_from_long(x):
    return _pmt_swig.pmt_from_long(x)
pmt_from_long = _pmt_swig.pmt_from_long

def pmt_to_long(x):
    return _pmt_swig.pmt_to_long(x)
pmt_to_long = _pmt_swig.pmt_to_long

def pmt_is_uint64(x):
    return _pmt_swig.pmt_is_uint64(x)
pmt_is_uint64 = _pmt_swig.pmt_is_uint64

def pmt_from_uint64(x):
    return _pmt_swig.pmt_from_uint64(x)
pmt_from_uint64 = _pmt_swig.pmt_from_uint64

def pmt_to_uint64(x):
    return _pmt_swig.pmt_to_uint64(x)
pmt_to_uint64 = _pmt_swig.pmt_to_uint64

def pmt_is_real(obj):
    return _pmt_swig.pmt_is_real(obj)
pmt_is_real = _pmt_swig.pmt_is_real

def pmt_from_double(x):
    return _pmt_swig.pmt_from_double(x)
pmt_from_double = _pmt_swig.pmt_from_double

def pmt_to_double(x):
    return _pmt_swig.pmt_to_double(x)
pmt_to_double = _pmt_swig.pmt_to_double

def pmt_is_complex(obj):
    return _pmt_swig.pmt_is_complex(obj)
pmt_is_complex = _pmt_swig.pmt_is_complex

def pmt_make_rectangular(re, im):
    return _pmt_swig.pmt_make_rectangular(re, im)
pmt_make_rectangular = _pmt_swig.pmt_make_rectangular

def pmt_to_complex(z):
    return _pmt_swig.pmt_to_complex(z)
pmt_to_complex = _pmt_swig.pmt_to_complex

def pmt_is_null(x):
    return _pmt_swig.pmt_is_null(x)
pmt_is_null = _pmt_swig.pmt_is_null

def pmt_is_pair(obj):
    return _pmt_swig.pmt_is_pair(obj)
pmt_is_pair = _pmt_swig.pmt_is_pair

def pmt_cons(x, y):
    return _pmt_swig.pmt_cons(x, y)
pmt_cons = _pmt_swig.pmt_cons

def pmt_car(pair):
    return _pmt_swig.pmt_car(pair)
pmt_car = _pmt_swig.pmt_car

def pmt_cdr(pair):
    return _pmt_swig.pmt_cdr(pair)
pmt_cdr = _pmt_swig.pmt_cdr

def pmt_set_car(pair, value):
    return _pmt_swig.pmt_set_car(pair, value)
pmt_set_car = _pmt_swig.pmt_set_car

def pmt_set_cdr(pair, value):
    return _pmt_swig.pmt_set_cdr(pair, value)
pmt_set_cdr = _pmt_swig.pmt_set_cdr

def pmt_caar(pair):
    return _pmt_swig.pmt_caar(pair)
pmt_caar = _pmt_swig.pmt_caar

def pmt_cadr(pair):
    return _pmt_swig.pmt_cadr(pair)
pmt_cadr = _pmt_swig.pmt_cadr

def pmt_cdar(pair):
    return _pmt_swig.pmt_cdar(pair)
pmt_cdar = _pmt_swig.pmt_cdar

def pmt_cddr(pair):
    return _pmt_swig.pmt_cddr(pair)
pmt_cddr = _pmt_swig.pmt_cddr

def pmt_caddr(pair):
    return _pmt_swig.pmt_caddr(pair)
pmt_caddr = _pmt_swig.pmt_caddr

def pmt_cadddr(pair):
    return _pmt_swig.pmt_cadddr(pair)
pmt_cadddr = _pmt_swig.pmt_cadddr

def pmt_is_tuple(x):
    return _pmt_swig.pmt_is_tuple(x)
pmt_is_tuple = _pmt_swig.pmt_is_tuple

def pmt_make_tuple(*args):
    return _pmt_swig.pmt_make_tuple(*args)
pmt_make_tuple = _pmt_swig.pmt_make_tuple

def pmt_to_tuple(x):
    return _pmt_swig.pmt_to_tuple(x)
pmt_to_tuple = _pmt_swig.pmt_to_tuple

def pmt_tuple_ref(tuple, k):
    return _pmt_swig.pmt_tuple_ref(tuple, k)
pmt_tuple_ref = _pmt_swig.pmt_tuple_ref

def pmt_is_vector(x):
    return _pmt_swig.pmt_is_vector(x)
pmt_is_vector = _pmt_swig.pmt_is_vector

def pmt_make_vector(k, fill):
    return _pmt_swig.pmt_make_vector(k, fill)
pmt_make_vector = _pmt_swig.pmt_make_vector

def pmt_vector_ref(vector, k):
    return _pmt_swig.pmt_vector_ref(vector, k)
pmt_vector_ref = _pmt_swig.pmt_vector_ref

def pmt_vector_set(vector, k, obj):
    return _pmt_swig.pmt_vector_set(vector, k, obj)
pmt_vector_set = _pmt_swig.pmt_vector_set

def pmt_vector_fill(vector, fill):
    return _pmt_swig.pmt_vector_fill(vector, fill)
pmt_vector_fill = _pmt_swig.pmt_vector_fill

def pmt_is_blob(x):
    return _pmt_swig.pmt_is_blob(x)
pmt_is_blob = _pmt_swig.pmt_is_blob

def pmt_make_blob(buf, len):
    return _pmt_swig.pmt_make_blob(buf, len)
pmt_make_blob = _pmt_swig.pmt_make_blob

def pmt_blob_data(blob):
    return _pmt_swig.pmt_blob_data(blob)
pmt_blob_data = _pmt_swig.pmt_blob_data

def pmt_blob_length(blob):
    return _pmt_swig.pmt_blob_length(blob)
pmt_blob_length = _pmt_swig.pmt_blob_length

def pmt_is_uniform_vector(x):
    return _pmt_swig.pmt_is_uniform_vector(x)
pmt_is_uniform_vector = _pmt_swig.pmt_is_uniform_vector

def pmt_is_u8vector(x):
    return _pmt_swig.pmt_is_u8vector(x)
pmt_is_u8vector = _pmt_swig.pmt_is_u8vector

def pmt_is_s8vector(x):
    return _pmt_swig.pmt_is_s8vector(x)
pmt_is_s8vector = _pmt_swig.pmt_is_s8vector

def pmt_is_u16vector(x):
    return _pmt_swig.pmt_is_u16vector(x)
pmt_is_u16vector = _pmt_swig.pmt_is_u16vector

def pmt_is_s16vector(x):
    return _pmt_swig.pmt_is_s16vector(x)
pmt_is_s16vector = _pmt_swig.pmt_is_s16vector

def pmt_is_u32vector(x):
    return _pmt_swig.pmt_is_u32vector(x)
pmt_is_u32vector = _pmt_swig.pmt_is_u32vector

def pmt_is_s32vector(x):
    return _pmt_swig.pmt_is_s32vector(x)
pmt_is_s32vector = _pmt_swig.pmt_is_s32vector

def pmt_is_u64vector(x):
    return _pmt_swig.pmt_is_u64vector(x)
pmt_is_u64vector = _pmt_swig.pmt_is_u64vector

def pmt_is_s64vector(x):
    return _pmt_swig.pmt_is_s64vector(x)
pmt_is_s64vector = _pmt_swig.pmt_is_s64vector

def pmt_is_f32vector(x):
    return _pmt_swig.pmt_is_f32vector(x)
pmt_is_f32vector = _pmt_swig.pmt_is_f32vector

def pmt_is_f64vector(x):
    return _pmt_swig.pmt_is_f64vector(x)
pmt_is_f64vector = _pmt_swig.pmt_is_f64vector

def pmt_is_c32vector(x):
    return _pmt_swig.pmt_is_c32vector(x)
pmt_is_c32vector = _pmt_swig.pmt_is_c32vector

def pmt_is_c64vector(x):
    return _pmt_swig.pmt_is_c64vector(x)
pmt_is_c64vector = _pmt_swig.pmt_is_c64vector

def pmt_make_u8vector(k, fill):
    return _pmt_swig.pmt_make_u8vector(k, fill)
pmt_make_u8vector = _pmt_swig.pmt_make_u8vector

def pmt_make_s8vector(k, fill):
    return _pmt_swig.pmt_make_s8vector(k, fill)
pmt_make_s8vector = _pmt_swig.pmt_make_s8vector

def pmt_make_u16vector(k, fill):
    return _pmt_swig.pmt_make_u16vector(k, fill)
pmt_make_u16vector = _pmt_swig.pmt_make_u16vector

def pmt_make_s16vector(k, fill):
    return _pmt_swig.pmt_make_s16vector(k, fill)
pmt_make_s16vector = _pmt_swig.pmt_make_s16vector

def pmt_make_u32vector(k, fill):
    return _pmt_swig.pmt_make_u32vector(k, fill)
pmt_make_u32vector = _pmt_swig.pmt_make_u32vector

def pmt_make_s32vector(k, fill):
    return _pmt_swig.pmt_make_s32vector(k, fill)
pmt_make_s32vector = _pmt_swig.pmt_make_s32vector

def pmt_make_u64vector(k, fill):
    return _pmt_swig.pmt_make_u64vector(k, fill)
pmt_make_u64vector = _pmt_swig.pmt_make_u64vector

def pmt_make_s64vector(k, fill):
    return _pmt_swig.pmt_make_s64vector(k, fill)
pmt_make_s64vector = _pmt_swig.pmt_make_s64vector

def pmt_make_f32vector(k, fill):
    return _pmt_swig.pmt_make_f32vector(k, fill)
pmt_make_f32vector = _pmt_swig.pmt_make_f32vector

def pmt_make_f64vector(k, fill):
    return _pmt_swig.pmt_make_f64vector(k, fill)
pmt_make_f64vector = _pmt_swig.pmt_make_f64vector

def pmt_make_c32vector(k, fill):
    return _pmt_swig.pmt_make_c32vector(k, fill)
pmt_make_c32vector = _pmt_swig.pmt_make_c32vector

def pmt_make_c64vector(k, fill):
    return _pmt_swig.pmt_make_c64vector(k, fill)
pmt_make_c64vector = _pmt_swig.pmt_make_c64vector

def pmt_init_u8vector(k, data):
    return _pmt_swig.pmt_init_u8vector(k, data)
pmt_init_u8vector = _pmt_swig.pmt_init_u8vector

def pmt_init_s8vector(k, data):
    return _pmt_swig.pmt_init_s8vector(k, data)
pmt_init_s8vector = _pmt_swig.pmt_init_s8vector

def pmt_init_u16vector(k, data):
    return _pmt_swig.pmt_init_u16vector(k, data)
pmt_init_u16vector = _pmt_swig.pmt_init_u16vector

def pmt_init_s16vector(k, data):
    return _pmt_swig.pmt_init_s16vector(k, data)
pmt_init_s16vector = _pmt_swig.pmt_init_s16vector

def pmt_init_u32vector(k, data):
    return _pmt_swig.pmt_init_u32vector(k, data)
pmt_init_u32vector = _pmt_swig.pmt_init_u32vector

def pmt_init_s32vector(k, data):
    return _pmt_swig.pmt_init_s32vector(k, data)
pmt_init_s32vector = _pmt_swig.pmt_init_s32vector

def pmt_init_f32vector(k, data):
    return _pmt_swig.pmt_init_f32vector(k, data)
pmt_init_f32vector = _pmt_swig.pmt_init_f32vector

def pmt_init_f64vector(k, data):
    return _pmt_swig.pmt_init_f64vector(k, data)
pmt_init_f64vector = _pmt_swig.pmt_init_f64vector

def pmt_init_c32vector(k, data):
    return _pmt_swig.pmt_init_c32vector(k, data)
pmt_init_c32vector = _pmt_swig.pmt_init_c32vector

def pmt_init_c64vector(k, data):
    return _pmt_swig.pmt_init_c64vector(k, data)
pmt_init_c64vector = _pmt_swig.pmt_init_c64vector

def pmt_u8vector_ref(v, k):
    return _pmt_swig.pmt_u8vector_ref(v, k)
pmt_u8vector_ref = _pmt_swig.pmt_u8vector_ref

def pmt_s8vector_ref(v, k):
    return _pmt_swig.pmt_s8vector_ref(v, k)
pmt_s8vector_ref = _pmt_swig.pmt_s8vector_ref

def pmt_u16vector_ref(v, k):
    return _pmt_swig.pmt_u16vector_ref(v, k)
pmt_u16vector_ref = _pmt_swig.pmt_u16vector_ref

def pmt_s16vector_ref(v, k):
    return _pmt_swig.pmt_s16vector_ref(v, k)
pmt_s16vector_ref = _pmt_swig.pmt_s16vector_ref

def pmt_u32vector_ref(v, k):
    return _pmt_swig.pmt_u32vector_ref(v, k)
pmt_u32vector_ref = _pmt_swig.pmt_u32vector_ref

def pmt_s32vector_ref(v, k):
    return _pmt_swig.pmt_s32vector_ref(v, k)
pmt_s32vector_ref = _pmt_swig.pmt_s32vector_ref

def pmt_u64vector_ref(v, k):
    return _pmt_swig.pmt_u64vector_ref(v, k)
pmt_u64vector_ref = _pmt_swig.pmt_u64vector_ref

def pmt_s64vector_ref(v, k):
    return _pmt_swig.pmt_s64vector_ref(v, k)
pmt_s64vector_ref = _pmt_swig.pmt_s64vector_ref

def pmt_f32vector_ref(v, k):
    return _pmt_swig.pmt_f32vector_ref(v, k)
pmt_f32vector_ref = _pmt_swig.pmt_f32vector_ref

def pmt_f64vector_ref(v, k):
    return _pmt_swig.pmt_f64vector_ref(v, k)
pmt_f64vector_ref = _pmt_swig.pmt_f64vector_ref

def pmt_c32vector_ref(v, k):
    return _pmt_swig.pmt_c32vector_ref(v, k)
pmt_c32vector_ref = _pmt_swig.pmt_c32vector_ref

def pmt_c64vector_ref(v, k):
    return _pmt_swig.pmt_c64vector_ref(v, k)
pmt_c64vector_ref = _pmt_swig.pmt_c64vector_ref

def pmt_u8vector_set(v, k, x):
    return _pmt_swig.pmt_u8vector_set(v, k, x)
pmt_u8vector_set = _pmt_swig.pmt_u8vector_set

def pmt_s8vector_set(v, k, x):
    return _pmt_swig.pmt_s8vector_set(v, k, x)
pmt_s8vector_set = _pmt_swig.pmt_s8vector_set

def pmt_u16vector_set(v, k, x):
    return _pmt_swig.pmt_u16vector_set(v, k, x)
pmt_u16vector_set = _pmt_swig.pmt_u16vector_set

def pmt_s16vector_set(v, k, x):
    return _pmt_swig.pmt_s16vector_set(v, k, x)
pmt_s16vector_set = _pmt_swig.pmt_s16vector_set

def pmt_u32vector_set(v, k, x):
    return _pmt_swig.pmt_u32vector_set(v, k, x)
pmt_u32vector_set = _pmt_swig.pmt_u32vector_set

def pmt_s32vector_set(v, k, x):
    return _pmt_swig.pmt_s32vector_set(v, k, x)
pmt_s32vector_set = _pmt_swig.pmt_s32vector_set

def pmt_u64vector_set(v, k, x):
    return _pmt_swig.pmt_u64vector_set(v, k, x)
pmt_u64vector_set = _pmt_swig.pmt_u64vector_set

def pmt_s64vector_set(v, k, x):
    return _pmt_swig.pmt_s64vector_set(v, k, x)
pmt_s64vector_set = _pmt_swig.pmt_s64vector_set

def pmt_f32vector_set(v, k, x):
    return _pmt_swig.pmt_f32vector_set(v, k, x)
pmt_f32vector_set = _pmt_swig.pmt_f32vector_set

def pmt_f64vector_set(v, k, x):
    return _pmt_swig.pmt_f64vector_set(v, k, x)
pmt_f64vector_set = _pmt_swig.pmt_f64vector_set

def pmt_c32vector_set(v, k, x):
    return _pmt_swig.pmt_c32vector_set(v, k, x)
pmt_c32vector_set = _pmt_swig.pmt_c32vector_set

def pmt_c64vector_set(v, k, x):
    return _pmt_swig.pmt_c64vector_set(v, k, x)
pmt_c64vector_set = _pmt_swig.pmt_c64vector_set

def pmt_uniform_vector_elements(v, len):
    return _pmt_swig.pmt_uniform_vector_elements(v, len)
pmt_uniform_vector_elements = _pmt_swig.pmt_uniform_vector_elements

def pmt_u8vector_elements(v, len):
    return _pmt_swig.pmt_u8vector_elements(v, len)
pmt_u8vector_elements = _pmt_swig.pmt_u8vector_elements

def pmt_s8vector_elements(v, len):
    return _pmt_swig.pmt_s8vector_elements(v, len)
pmt_s8vector_elements = _pmt_swig.pmt_s8vector_elements

def pmt_u16vector_elements(v, len):
    return _pmt_swig.pmt_u16vector_elements(v, len)
pmt_u16vector_elements = _pmt_swig.pmt_u16vector_elements

def pmt_s16vector_elements(v, len):
    return _pmt_swig.pmt_s16vector_elements(v, len)
pmt_s16vector_elements = _pmt_swig.pmt_s16vector_elements

def pmt_u32vector_elements(v, len):
    return _pmt_swig.pmt_u32vector_elements(v, len)
pmt_u32vector_elements = _pmt_swig.pmt_u32vector_elements

def pmt_s32vector_elements(v, len):
    return _pmt_swig.pmt_s32vector_elements(v, len)
pmt_s32vector_elements = _pmt_swig.pmt_s32vector_elements

def pmt_u64vector_elements(v, len):
    return _pmt_swig.pmt_u64vector_elements(v, len)
pmt_u64vector_elements = _pmt_swig.pmt_u64vector_elements

def pmt_s64vector_elements(v, len):
    return _pmt_swig.pmt_s64vector_elements(v, len)
pmt_s64vector_elements = _pmt_swig.pmt_s64vector_elements

def pmt_f32vector_elements(v, len):
    return _pmt_swig.pmt_f32vector_elements(v, len)
pmt_f32vector_elements = _pmt_swig.pmt_f32vector_elements

def pmt_f64vector_elements(v, len):
    return _pmt_swig.pmt_f64vector_elements(v, len)
pmt_f64vector_elements = _pmt_swig.pmt_f64vector_elements

def pmt_c32vector_elements(v, len):
    return _pmt_swig.pmt_c32vector_elements(v, len)
pmt_c32vector_elements = _pmt_swig.pmt_c32vector_elements

def pmt_c64vector_elements(v, len):
    return _pmt_swig.pmt_c64vector_elements(v, len)
pmt_c64vector_elements = _pmt_swig.pmt_c64vector_elements

def pmt_uniform_vector_writable_elements(v, len):
    return _pmt_swig.pmt_uniform_vector_writable_elements(v, len)
pmt_uniform_vector_writable_elements = _pmt_swig.pmt_uniform_vector_writable_elements

def pmt_u8vector_writable_elements(v, len):
    return _pmt_swig.pmt_u8vector_writable_elements(v, len)
pmt_u8vector_writable_elements = _pmt_swig.pmt_u8vector_writable_elements

def pmt_s8vector_writable_elements(v, len):
    return _pmt_swig.pmt_s8vector_writable_elements(v, len)
pmt_s8vector_writable_elements = _pmt_swig.pmt_s8vector_writable_elements

def pmt_u16vector_writable_elements(v, len):
    return _pmt_swig.pmt_u16vector_writable_elements(v, len)
pmt_u16vector_writable_elements = _pmt_swig.pmt_u16vector_writable_elements

def pmt_s16vector_writable_elements(v, len):
    return _pmt_swig.pmt_s16vector_writable_elements(v, len)
pmt_s16vector_writable_elements = _pmt_swig.pmt_s16vector_writable_elements

def pmt_u32vector_writable_elements(v, len):
    return _pmt_swig.pmt_u32vector_writable_elements(v, len)
pmt_u32vector_writable_elements = _pmt_swig.pmt_u32vector_writable_elements

def pmt_s32vector_writable_elements(v, len):
    return _pmt_swig.pmt_s32vector_writable_elements(v, len)
pmt_s32vector_writable_elements = _pmt_swig.pmt_s32vector_writable_elements

def pmt_u64vector_writable_elements(v, len):
    return _pmt_swig.pmt_u64vector_writable_elements(v, len)
pmt_u64vector_writable_elements = _pmt_swig.pmt_u64vector_writable_elements

def pmt_s64vector_writable_elements(v, len):
    return _pmt_swig.pmt_s64vector_writable_elements(v, len)
pmt_s64vector_writable_elements = _pmt_swig.pmt_s64vector_writable_elements

def pmt_f32vector_writable_elements(v, len):
    return _pmt_swig.pmt_f32vector_writable_elements(v, len)
pmt_f32vector_writable_elements = _pmt_swig.pmt_f32vector_writable_elements

def pmt_f64vector_writable_elements(v, len):
    return _pmt_swig.pmt_f64vector_writable_elements(v, len)
pmt_f64vector_writable_elements = _pmt_swig.pmt_f64vector_writable_elements

def pmt_c32vector_writable_elements(v, len):
    return _pmt_swig.pmt_c32vector_writable_elements(v, len)
pmt_c32vector_writable_elements = _pmt_swig.pmt_c32vector_writable_elements

def pmt_c64vector_writable_elements(v, len):
    return _pmt_swig.pmt_c64vector_writable_elements(v, len)
pmt_c64vector_writable_elements = _pmt_swig.pmt_c64vector_writable_elements

def pmt_is_dict(obj):
    return _pmt_swig.pmt_is_dict(obj)
pmt_is_dict = _pmt_swig.pmt_is_dict

def pmt_make_dict():
    return _pmt_swig.pmt_make_dict()
pmt_make_dict = _pmt_swig.pmt_make_dict

def pmt_dict_add(dict, key, value):
    return _pmt_swig.pmt_dict_add(dict, key, value)
pmt_dict_add = _pmt_swig.pmt_dict_add

def pmt_dict_delete(dict, key):
    return _pmt_swig.pmt_dict_delete(dict, key)
pmt_dict_delete = _pmt_swig.pmt_dict_delete

def pmt_dict_has_key(dict, key):
    return _pmt_swig.pmt_dict_has_key(dict, key)
pmt_dict_has_key = _pmt_swig.pmt_dict_has_key

def pmt_dict_ref(dict, key, not_found):
    return _pmt_swig.pmt_dict_ref(dict, key, not_found)
pmt_dict_ref = _pmt_swig.pmt_dict_ref

def pmt_dict_items(dict):
    return _pmt_swig.pmt_dict_items(dict)
pmt_dict_items = _pmt_swig.pmt_dict_items

def pmt_dict_keys(dict):
    return _pmt_swig.pmt_dict_keys(dict)
pmt_dict_keys = _pmt_swig.pmt_dict_keys

def pmt_dict_values(dict):
    return _pmt_swig.pmt_dict_values(dict)
pmt_dict_values = _pmt_swig.pmt_dict_values

def pmt_is_any(obj):
    return _pmt_swig.pmt_is_any(obj)
pmt_is_any = _pmt_swig.pmt_is_any

def pmt_make_any(any):
    return _pmt_swig.pmt_make_any(any)
pmt_make_any = _pmt_swig.pmt_make_any

def pmt_any_ref(obj):
    return _pmt_swig.pmt_any_ref(obj)
pmt_any_ref = _pmt_swig.pmt_any_ref

def pmt_any_set(obj, any):
    return _pmt_swig.pmt_any_set(obj, any)
pmt_any_set = _pmt_swig.pmt_any_set

def pmt_is_msg_accepter(obj):
    return _pmt_swig.pmt_is_msg_accepter(obj)
pmt_is_msg_accepter = _pmt_swig.pmt_is_msg_accepter

def pmt_make_msg_accepter(ma):
    return _pmt_swig.pmt_make_msg_accepter(ma)
pmt_make_msg_accepter = _pmt_swig.pmt_make_msg_accepter

def pmt_msg_accepter_ref(obj):
    return _pmt_swig.pmt_msg_accepter_ref(obj)
pmt_msg_accepter_ref = _pmt_swig.pmt_msg_accepter_ref

def pmt_eq(x, y):
    return _pmt_swig.pmt_eq(x, y)
pmt_eq = _pmt_swig.pmt_eq

def pmt_eqv(x, y):
    return _pmt_swig.pmt_eqv(x, y)
pmt_eqv = _pmt_swig.pmt_eqv

def pmt_equal(x, y):
    return _pmt_swig.pmt_equal(x, y)
pmt_equal = _pmt_swig.pmt_equal

def pmt_length(v):
    return _pmt_swig.pmt_length(v)
pmt_length = _pmt_swig.pmt_length

def pmt_assq(obj, alist):
    return _pmt_swig.pmt_assq(obj, alist)
pmt_assq = _pmt_swig.pmt_assq

def pmt_assv(obj, alist):
    return _pmt_swig.pmt_assv(obj, alist)
pmt_assv = _pmt_swig.pmt_assv

def pmt_assoc(obj, alist):
    return _pmt_swig.pmt_assoc(obj, alist)
pmt_assoc = _pmt_swig.pmt_assoc

def pmt_map(proc, list):
    return _pmt_swig.pmt_map(proc, list)
pmt_map = _pmt_swig.pmt_map

def pmt_reverse(list):
    return _pmt_swig.pmt_reverse(list)
pmt_reverse = _pmt_swig.pmt_reverse

def pmt_reverse_x(list):
    return _pmt_swig.pmt_reverse_x(list)
pmt_reverse_x = _pmt_swig.pmt_reverse_x

def pmt_acons(x, y, a):
    return _pmt_swig.pmt_acons(x, y, a)
pmt_acons = _pmt_swig.pmt_acons

def pmt_nth(n, list):
    return _pmt_swig.pmt_nth(n, list)
pmt_nth = _pmt_swig.pmt_nth

def pmt_nthcdr(n, list):
    return _pmt_swig.pmt_nthcdr(n, list)
pmt_nthcdr = _pmt_swig.pmt_nthcdr

def pmt_memq(obj, list):
    return _pmt_swig.pmt_memq(obj, list)
pmt_memq = _pmt_swig.pmt_memq

def pmt_memv(obj, list):
    return _pmt_swig.pmt_memv(obj, list)
pmt_memv = _pmt_swig.pmt_memv

def pmt_member(obj, list):
    return _pmt_swig.pmt_member(obj, list)
pmt_member = _pmt_swig.pmt_member

def pmt_subsetp(list1, list2):
    return _pmt_swig.pmt_subsetp(list1, list2)
pmt_subsetp = _pmt_swig.pmt_subsetp

def pmt_list1(x1):
    return _pmt_swig.pmt_list1(x1)
pmt_list1 = _pmt_swig.pmt_list1

def pmt_list2(x1, x2):
    return _pmt_swig.pmt_list2(x1, x2)
pmt_list2 = _pmt_swig.pmt_list2

def pmt_list3(x1, x2, x3):
    return _pmt_swig.pmt_list3(x1, x2, x3)
pmt_list3 = _pmt_swig.pmt_list3

def pmt_list4(x1, x2, x3, x4):
    return _pmt_swig.pmt_list4(x1, x2, x3, x4)
pmt_list4 = _pmt_swig.pmt_list4

def pmt_list5(x1, x2, x3, x4, x5):
    return _pmt_swig.pmt_list5(x1, x2, x3, x4, x5)
pmt_list5 = _pmt_swig.pmt_list5

def pmt_list6(x1, x2, x3, x4, x5, x6):
    return _pmt_swig.pmt_list6(x1, x2, x3, x4, x5, x6)
pmt_list6 = _pmt_swig.pmt_list6

def pmt_list_add(list, item):
    return _pmt_swig.pmt_list_add(list, item)
pmt_list_add = _pmt_swig.pmt_list_add

def pmt_is_eof_object(obj):
    return _pmt_swig.pmt_is_eof_object(obj)
pmt_is_eof_object = _pmt_swig.pmt_is_eof_object

def pmt_read(port):
    return _pmt_swig.pmt_read(port)
pmt_read = _pmt_swig.pmt_read

def pmt_write(obj, port):
    return _pmt_swig.pmt_write(obj, port)
pmt_write = _pmt_swig.pmt_write

def pmt_write_string(obj):
    return _pmt_swig.pmt_write_string(obj)
pmt_write_string = _pmt_swig.pmt_write_string

def pmt_print(v):
    return _pmt_swig.pmt_print(v)
pmt_print = _pmt_swig.pmt_print

def pmt_serialize(obj, sink):
    return _pmt_swig.pmt_serialize(obj, sink)
pmt_serialize = _pmt_swig.pmt_serialize

def pmt_deserialize(source):
    return _pmt_swig.pmt_deserialize(source)
pmt_deserialize = _pmt_swig.pmt_deserialize

def pmt_dump_sizeof():
    return _pmt_swig.pmt_dump_sizeof()
pmt_dump_sizeof = _pmt_swig.pmt_dump_sizeof

def pmt_serialize_str(obj):
    return _pmt_swig.pmt_serialize_str(obj)
pmt_serialize_str = _pmt_swig.pmt_serialize_str

def pmt_deserialize_str(str):
    return _pmt_swig.pmt_deserialize_str(str)
pmt_deserialize_str = _pmt_swig.pmt_deserialize_str

cvar = _pmt_swig.cvar
PMT_T = cvar.PMT_T
PMT_F = cvar.PMT_F
PMT_NIL = cvar.PMT_NIL
PMT_EOF = cvar.PMT_EOF

