#!/bin/sh

# 1st parameter is absolute path to component source directory
# 2nd parameter is absolute path to component build directory
# 3rd parameter is path to Python QA directory

# For OS/X
DYLD_LIBRARY_PATH=/home/me/gnuradio-3.4.0/usrp2/host/lib:/home/me/gnuradio-3.4.0/usrp2/host/lib/.libs:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH

# For Win32
PATH=/home/me/gnuradio-3.4.0/usrp2/host/lib:/home/me/gnuradio-3.4.0/usrp2/host/lib/.libs:$PATH

../../run_tests.sh \
    /home/me/gnuradio-3.4.0/gr-usrp2 \
    /home/me/gnuradio-3.4.0/gr-usrp2 \
    .
